ZupIT/beagle

android/beagle/src/main/java/br/com/zup/beagle/engine/renderer/layout/ScreenViewRenderer.kt, android/beagle/src/main/java/br/com/zup/beagle/utils/ToolbarManager.kt, android/beagle/src/main/res/values/attrs.xml, android/beagle/src/test/java/br/com/zup/beagle/engine/renderer/layout/ScreenViewRendererTest.kt, android/beagle/src/test/java/br/com/zup/beagle/utils/ToolbarManagerTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/AppDesignSystem.kt, android/sample/src/main/res/values/styles.xml
=> Added centerTitle attribute to Toolbar style

fastlane/Fastfile, fastlane/get_previous_tag.sh
Created a little script to get first commit when not existing previous tag
=> Create script to get first commit or previous tag

android/android-processor/build.gradle, android/android-processor/src/main/java/br/com/zup/beagle/compiler/BeagleAnnotationProcessor.kt, buildSrc/src/main/java/Dependencies.kt
The library [incap](https://github.com/tbroyer/gradle-incap-helper) help us to add support for building incremental annotation processors.
https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing
https://github.com/ZupIT/beagle/issues/3
=> Add support to incremental annotation processing

iOS/Sources/BeagleUI/Sources/Components/Layout/Flex/FlexViewConfigurator.swift, iOS/Sources/BeagleUI/Sources/Components/Layout/Flex/Tests/FlexViewConfiguratorTests.swift
#125
**Problem:**
The position has an EdgeValue property where we have the attributes, but not all attributes are functional.Position does not implement all properties.
**Solution:**
The solution was to implement these atributtes on iOS, since we had them on Android
=> fix: implements all, horizontal, vertical in flex position

backend/processor/src/main/kotlin/br/com/zup/beagle/compiler/BeagleBackendProcessor.kt, backend/sample/core/build.gradle, common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleWidgetBindingHandler.kt
Fixes android studio support for generated classes
=> feat: Fixes android studio support for generated classes

android/beagle/src/main/java/br/com/zup/beagle/data/serializer/adapter/ComponentJsonAdapterFactory.kt
#247 
Problem:
Webview component does not deserialize.
Solution:
Registered the component in the deserializer
=> fix: webview component does not deserialize

android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/LazyComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/NetworkImage.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Spacer.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Touchable.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/Form.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormSubmit.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ComponentScreenBuilder.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/WebViewScreenBuilder.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/constants/PathConstants.kt, backend/sample/micronaut/src/main/kotlin/br/com/zup/beagle/sample/micronaut/controller/ScreenController.kt, backend/sample/micronaut/src/main/kotlin/br/com/zup/beagle/sample/micronaut/service/WebViewService.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/controller/ScreenController.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/service/SampleWebViewService.kt
#242 
**Problem**
Attributes classes components are private.
Outdated sample, missing webview component .
**Solution**
Adding the web view component to the sample.
Changed private to public methods.
=> fix: Implemented the web view component  to the sample and corrected private attributes

android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/BindAdapterFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/StringExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/StringExtensionsKtTest.kt
In the actual context we do not support expression like this `Hello @{myContext.name}`.
ContextDataHandler is not responsible to handle multiple expressions like this above.
=> feat: Create multiple expression logic

CODEOWNERS
=> fix: update codeowners

.github/dco.yml
this will be disable DCO to organization
=> feat: disable dco to members of organization

android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/ViewExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BindExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/StyleManager.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/StyleManagerTest.kt
Adds android implementation for the bind attributes of button
https://github.com/ZupIT/beagle/issues/283
=> feat: Adds android implementation for the bind attributes of button

android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/WebView.kt
Adds schema/android implementation for Bind attributes of WebView Widget 
#283
=> feat: Adds schema/android implementation for Bind attributes of WebView Widget

android/beagle/src/main/java/br/com/zup/beagle/android/components/Text.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/StyleManager.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/Text.kt
Adds schema/android implementation for Bind attributes of Text widget
https://github.com/ZupIT/beagle/issues/283
=> feat: Adds schema/android implementation for Bind attributes of Text widget

android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/AlertTest.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Alert.kt
Adds schema/android implementation for Bind attributes of Alert action
Signed-off-by: Hernand Azevedo <hernand.azevedo@zup.com.br>
=> feat: Adds schema/android implementation for Bind attributes of Alert action

android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/ConfirmTest.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Confirm.kt
Signed-off-by: Hernand Azevedo <hernand.azevedo@zup.com.br>
=> feat: Adds schema/android implementation for Bind attributes of Confirm action

android/beagle/src/main/java/br/com/zup/beagle/android/engine/mapper/FlexMapper.kt, android/beagle/src/test/java/br/com/zup/beagle/android/engine/mapper/FlexMapperTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/DisabledFormSubmitFragment.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/TextScreenBuilder.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/FlexBuilder.kt
closes #325 
BREAKING CHANGE:  Not has support edgevalue property start and end support attribute
=> refactor: remove support attribute start and end property edgevalue

android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/StyleManager.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/TabViewTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/TabView.kt
feat: Adds schema/android implementation for Bind attributes of TabView Widget
#283
=> feat: Adds schema/android implementation for Bind attributes of TabView Widget

.github/dco.yml
##Notes
The tab indentation is wrong.
=> refactor: update dco.yml

iOS/Example/BeagleDemo/BeagleDemo/Screens/FormScreen.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/LazyComponentScreen.swift, iOS/Schema/Sources/Action/Types/SendRequest.swift, iOS/Sources/BeagleUI/Sources/Action/Types/Alert.swift, iOS/Sources/BeagleUI/Sources/Action/Types/Confirm.swift, iOS/Sources/BeagleUI/Sources/Components/TabBar+Renderable/TabViewUIComponent.swift
**Problems**
- Alert and Confirm: bug in guard let.
- SendRequest: Decoding errors.
- Demo: Fixes in Form.
=> fix: Components Alerts and SendRequest

common/processor-utils/gradle.properties
Fix incorrectly duplicated artifact name.
=> fix: artifact names

android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SetContext.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BindExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/StringExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/StringExtensionsKtTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/widgets/Input.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SendRequest.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SetContext.kt
**Description**
The `SendRequest` and `SetContext` actions now receive any value and before executing their respective actions, all the expressions present in them are evaluated.
=> feat: complex object evaluation

android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextActionExecutor.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SendRequestHandlerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextActionExecutorTest.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SendRequest.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ActionScreenBuilder.kt
=> refactor: change attribute sendRequest onSuccess, onError and onFinish

android/beagle/src/main/java/br/com/zup/beagle/android/view/ViewFactory.kt
webview was crashing on android 21
Fixes #333
=> fix: webview crash on android 21

iOS/Sources/BeagleUI/Sources/Action/Tests/TouchableTests.swift, iOS/Sources/BeagleUI/Sources/Action/Touchable+Renderable.swift
Touchable not working when the child is an Image
Make Touchable enable user interaction in the child view
=> fix: Touchable not working in some components

android/beagle/src/main/java/br/com/zup/beagle/android/engine/mapper/FlexMapper.kt
Fixes flex shrink that causes pageindicator bug, also other flex bugs due to default values being ignored
#249
=> fix: Fixes flex shrink that causes pageindicator bug, also other flex bugs due to default values being ignored

android/beagle/src/main/java/br/com/zup/beagle/android/engine/mapper/FlexMapper.kt
Fixes flex conflict with grow and shrink
=> fix: Fixes flex conflict with grow and shrink

android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataTreeHelperTest.kt
=> fix: show expression when change the tree and evaluate

android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScrollViewTest.kt
This PR fix a bug in the `ScrollView` that did not render correctly when assigned a horizontal axis.
=> fix: scroll view with horizontal axis

iOS/Example/BeagleDemo/BeagleDemo/Screens/TabViewScreen.swift, iOS/Sources/BeagleUI/Sources/Components/TabBar+Renderable/TabView.swift, iOS/Sources/BeagleUI/Sources/Components/TabBar+Renderable/TabViewUIComponent.swift
**Problem**
- Currently when a tab item has a TabView as a child it rendered this TabView without a width.
=> fix: TabView width fix

backend/sample/micronaut/src/main/resources/application.properties, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/config/CorsConfig.kt
Adding Cors support for the sample
=> feat: cors support

android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt
=> fix: add support to javascript in webview

iOS/Schema/Sources/Action/Types/Navigate/Navigate.swift, iOS/Sources/Beagle/Sources/Caching/Prefetch/Tests/BeaglePrefetchHelperTests.swift
**Problem**
Error decoding parameters url.
=> fix: Navigate decoding error

android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt
When some request fail and send empty data the mapper send a crash to app
=> fix: adjust crash when some error happen in request

iOS/Example/BeagleDemo/BeagleDemo/Screens/TabViewScreen.swift, iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Schema/Sources/ServerDrivenComponent/Screen/NavigationBar.swift, iOS/Schema/Sources/ServerDrivenComponent/TabBar/TabView.swift, iOS/Schema/Sources/ServerDrivenComponent/TabBar/Tests/__Snapshots__/TabViewTests/test_whenDecodingJson_thenItShouldReturnATabView.1.txt, iOS/Schema/Sources/Widgets/Image/Image.swift, iOS/Schema/Sources/Widgets/Image/Tests/JSON/ImageComponent.json, iOS/Schema/Sources/Widgets/Image/Tests/__Snapshots__/ImageTests/test_whenDecodingJson_thenItShouldReturnAnImage.1.txt, iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift, iOS/Sources/Beagle/Sources/Components/Image+Renderable/Tests/ImageTests.swift, iOS/Sources/Beagle/Sources/Components/Image+Renderable/Tests/JSON/ImageComponent.json, iOS/Sources/Beagle/Sources/Components/Image+Renderable/Tests/JSON/ImageComponent1.json, iOS/Sources/Beagle/Sources/Components/Image+Renderable/Tests/JSON/ImageComponent2.json, iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Screen/NavigationBar+UIKit.swift, iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarCollectionViewCell.swift, iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/Tests/TabBarCollectionViewCellTests.swift, iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/Tests/TabViewTests.swift
**Changes**
- Image parameter contentMode is now mode.
- Decoding of local Image type to improve usage, now Local is no longer an object and it decodes mobileId string directly in the places that use local type.
=> fix: image decoding error 

android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Touchable.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormSubmit.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt, build.gradle
=> fix: adjust render in touchable and in image network

iOS/Schema/Sources/ServerDrivenComponent/Screen/NavigationBar.swift, iOS/Schema/Sources/ServerDrivenComponent/TabBar/TabView.swift, iOS/Schema/Sources/Widgets/Image/Image.swift
=> fix: image decoding fix

README.md
In readme.md found 2 instances of the word 'begle', and fixed for Beagle
=> chore: fix begle word for Beagle

.github/PULL_REQUEST_TEMPLATE.md
=> chore: create PR template

CODE_OF_CONDUCT.md, README.md
=> chore: create code of conduct

android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ActionRequestViewModel.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
I modified the BeagleViewModel and ActionRequestViewModel, changing the way that was setting the LiveData value
fix issue: #409
Don't has test to this part, I just run the operations local and remote to check if the behavior continues works
=> fix: NavigationBar not showing NavigationBarItems

.github/labeler.yml, .github/workflows/label.yml
Automate the labeling of pull requests according to the directories modified.
Closes #416.
No tests added to the test suite.
I performed a simple usage test, by having the created action run in this very pull request.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant check boxes (`[x]`). This will ensure a smooth and quick review process.
=> chore: automatically label PRs

.github/labeler.yml, android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/Image.kt
Fixed the regexps used in the labeling configuration to consider subfolders as well.
None.
Created a simple formatting commit to test the action.
=> fix: label action's regexps

.github/workflows/sync_micronaut_sample.yml, .github/workflows/sync_spring_sample.yml
Stop triggering the BFF sample sync actions on pushes to master.
None.
None.
=> fix: ignoring push events for master

backend/sample/micronaut/src/main/kotlin/br/com/zup/beagle/sample/micronaut/controller/CustomComponentController.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/controller/CustomComponentController.kt, fastlane/Fastfile
Added missing extension in Fastfile sync_to_spring lane.
None.
A simple commit to trigger the action.
=> fix: typo in git_commit.sh in Fastfile

android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
Adjust Image to load path when it is not a complete url.
Not has.
Create a component Image with the path relative
=> fix: adjust url remote

android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
Fix issue #451 
Created test case for this case.
=> fix: string evaluation for JSON

.github/labeler.yml, .github/workflows/android-pr.yml, .github/workflows/backend-pr.yml, backend/sample/spring/build.gradle, buildSrc/src/main/java/Dependencies.kt
Signed-off-by: José Augusto <ze12augusto@gmail.com>
*Update spring and micronaut starter versions.*
Fixes: #523 
*Tested with spring versions until 2.1.15 and micronaut 1.3.
=> feat: Update spring and micronaut starters vesions

android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SetContext.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/BindAdapterFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SendRequestTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SetContextTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/testutil/RandomData.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/WidgetExtensionsKtTest.kt
After some changes in the context, we inserted a new bug that does not handle correctly context In the root of SendRequest and SetContext.
Fixes: #546
Created more test for all scenarios that we were not handling.
=> fix: Context for SendRequest and SetContext

README.md, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/compose/CustomComposeComponent.kt, codecov.yml
Added missing Codecov badge in README and backend coverage settings.
None.
A simple commit to trigger backend CI, testing Codecov settings.
Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
=> fix: codecov badge and backend settings

android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
fix: Fixes bug related to fetch components done at wrong moments 
Signed-off-by: Hernand Azevedo <hernand.azevedo@zup.com.br>
Fixes bug related to fetch components done at wrong moments
#576 
=> fix: Fixes bug related to fetch components done at wrong moments 

android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Text.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BindExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/WidgetExtensionsKtTest.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/FormScreenBuilder.kt
If an expression is not resolved returns null, when inside a string of multiple expressions return empty string. 
#502 #537
change ContextDataEvaluationTest
=> feat: Expression evaluates null

android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/FormLocalAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Touchable.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/Form.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/SimpleForm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextActionExecutor.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/AlertTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/ConfirmTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SendRequestTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/TouchableTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/form/FormTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextActionExecutorTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/widgets/Input.kt
Swap and depreciate the eventName and eventValue properties from the handleEvent extensions to the ContextData property
https://github.com/ZupIT/beagle/issues/592
Updated SendRequest class tests
=> fix: update handleEvent params

android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt
Changes `ToolbarManager` to center its title like iOS apps.
https://github.com/ZupIT/beagle/issues/478
No tests added
=> fix: Toolbar with centralized title

android/beagle/src/main/java/br/com/zup/beagle/android/action/SubmitForm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/Form.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormSubmit.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/SimpleForm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/core/FormValidatorController.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/ViewExtensions.kt, android/beagle/src/main/res/values/ids.xml, android/beagle/src/test/java/br/com/zup/beagle/android/action/FormValidationTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SubmitFormTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/BaseComponentTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/form/FormInputTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/form/FormSubmitTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/form/FormTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/form/core/FormValidatorControllerTest.kt
Adds extension variable for beagleComponent on View class. To set the tag with the associated resourceId.
=> fix: Adds extension variable for beagleComponent on View class. To set the tag with the resourceId

android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageViewTwo.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/page/PageViewTwoTest.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/PageViewScreenBuilder.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/PageView.kt
I create the showArrow attribute on declarative to indicate if the pageview arrows that are shown on the web should or not be visible, and change the implicit context name to be the same as the event name
#634 
No test was added
=> fix: page view

iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBar+Renderable.swift
Merging PR #613 and #620 resulted in a compilation error.
N/A
=> fix: tab null validation

iOS/Schema/Sources/ContextExpression/DynamicObject.swift, iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj, iOS/Sources/Beagle/Sources/Action/Types/SendRequest.swift, iOS/Sources/Beagle/Sources/Action/Types/Tests/SendRequestTests.swift, iOS/Sources/Beagle/Sources/Action/Types/Tests/__Snapshots__/SendRequestTests/test_whenSendRequestWithError_shouldDoRequestAndTriggerActions.1.txt, iOS/Sources/Beagle/Sources/Action/Types/Tests/__Snapshots__/SendRequestTests/test_whenSendRequestWithSuccess_shouldDoRequestAndTriggerActions.1.txt, iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Style/Tests/ContainerTests.swift
=> fix: SendRequest deserialization

android/beagle/src/main/java/br/com/zup/beagle/android/components/form/SimpleForm.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/form/SimpleForm.kt
Context attribute required in simpleform component change to Context attribute not required in simpleform component
closes #674 
Tests not changed
=> refactor: Context attribute not required in simpleform component

backend/widgets/build.gradle
fixed dependencies on backend widget
*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*
*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors.
- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x ] I …
=> fix: fixed dependencies on backend widget

backend/sample/micronaut/src/main/kotlin/br/com/zup/beagle/sample/micronaut/service/PlatformService.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/controller/DslController.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/service/PlatformService.kt, backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/service/SampleDslService.kt, fastlane/git_commit.sh
Configured automatic commit script to configure Beagle user locally.
None.
Simple commit to trigger the bot.
=> fix: configured Beagle user for automatic commits

README.md
*Removing release badge until our release workflow was stable, now its failing*
=> fix: Removing release badge

iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Schema/Sources/Widgets/Image/Image.swift, iOS/Schema/Sources/Widgets/Image/Tests/__Snapshots__/ImageTests/test_whenDecodingJson_thenItShouldReturnAnImage.1.txt
Changed the name from PathType to ImagePath to match with the backend.
resolves: #669 
=> fix: changed name of PathType to ImagePath

iOS/Sources/Beagle/Sources/ContextExpression/UIView+Context.swift
=> fix: Context DynamicObject transform in iOS 12 prior

fastlane/Fastfile
Signed-off-by: Victor Rabelo <victor.rabelo@zup.com.br>
removed extra character in release lane
=> ci: delete extra ',' in Fastfile

.github/workflows/release.yml
Adjust workflow release to set env variables
=> fix: set secret keys in env variables

CODEOWNERS
Added backend codeowner.
None.
None.
=> chore: add backend code owner

schema/schema-ruby-erb/Model Generation/FileHandler/file_handler.rb, schema/schema-ruby-erb/Model Generation/main.rb
* fixed bug where creating files on non existing directories were not working
=> fixed bug where creating files on non existing directories were not working

README.md
Some that were pointing to DOCs were broken
No related issue
=> fix: Links were updated

android/jacoco-android.gradle
This is a temporary solution to ignore some classes in `codecov`.
=> fix: adjust codecov to ignore some classes because they need to run in instrumentation test

codecov.yml
=> fix: adjust flag codecov

fastlane/Fastfile
Fix a bug in version name for Hotfix
=> fix: Remove - from version name

fastlane/Fastfile
Fix  version name when splitting Hotfix branch
=> fix: Version name remove slash before split

fastlane/Fastfile
Add split by `/` to tag name before split by `-`.
=> fix: Fastlane version generator

schema/schema-ruby-erb/Model Generation/Tests/Kotlin/test.sh
Created a shell script that copies the generated Kotlin schemas to their target directory, handling package to directory conversion.
#712 
None.
=> feat: shell script to integrate Kotlin schema

android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ImageViewFragment.kt
Closes #783
Fix image load in declarative android with place holder and error.
=> fix: show place holder and error when loading and the request url error

android/beagle/src/main/java/br/com/zup/beagle/android/action/AddChildrenAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java, android/beagle/src/test/java/br/com/zup/beagle/android/action/AddChildrenActionTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TextInputFragment.kt, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ButtonScreenBuilder.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/AddChildrenAction.kt
#272 
Create a addChildrenAction to add a list of ServerDrivenComponent on the views tree
=> feat: add children action on Android

android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleView.kt, android/sample/src/main/java/br/com/zup/beagle/sample/MainActivity.kt
=> fix: adjust import android

iOS/Sources/Beagle/Sources/Components/Text+Renderable/Text+Renderable.swift
=> fix: Text dark mode behavior

iOS/Example/BeagleDemo/.swiftlint.yml, iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/project.pbxproj, iOS/Example/BeagleDemo/BeagleDemo/Constants/Constants.swift, iOS/Example/BeagleDemo/BeagleDemo/DesignSystem/DSCollection/DSCollection.swift, iOS/Example/BeagleDemo/BeagleDemo/DesignSystem/DSCollection/DSCollectionViewCell.swift, iOS/Example/BeagleDemo/BeagleDemo/DesignSystem/ErrorView.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/ScreenDeepLink.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/SendRequestScreen.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/SimpleForm.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/ViewLayoutHelper.swift, iOS/Sources/Beagle/Sources/Common/Loading/LoadingView.swift
No related issue
Adds SwiftLint to BeagleDemo and corrects the necessary files.
=> chore: Adding SwiftLint to BeagleDemo

android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ActionRequestViewModel.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/SendRequestTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/ActionRequestViewModelTest.kt
A lot of work was being done on the main thread because the SendRequest actions and the fetching of components are not on IO threads.
=> fix: removed background work from main thread

android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ImplicitContextManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ImplicitContextManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ViewExtensionsKtTest.kt
This PR solves some issues related to lists inside lists.
=> fix: Context data manager

android/sample/src/main/java/br/com/zup/beagle/sample/actions/CustomAndroidAction.kt, common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/RegisteredActionGenerator.kt
Adjust class to project compile when registering some custom action
=> fix: adjust action generator

android/beagle/src/main/java/br/com/zup/beagle/android/context/tokenizer/TokenInterpreter.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/tokenizer/TokenParserTest.kt
Closes #846 
Adjust algorithm to scape single quote
=> fix: escape string literal

Beagle.podspec, BeagleSchema.podspec, fastlane/Fastfile, iOS/Sources/Beagle/Sources/Renderer/BeagleRenderer.swift
=> chore: merge release/1.2.1-iOS hotfix with master

android/beagle/src/main/java/br/com/zup/beagle/android/cache/CacheManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/cache/LruCacheStore.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextBinding.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/ComponentRequester.kt, android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleConfig.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/DatabaseLocalStore.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/LocalStore.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/MemoryLocalStore.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/StoreHandler.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/StoreHandlerDefault.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt, android/beagle/src/test/java/br/com/zup/beagle/android/BaseTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/cache/CacheManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/cache/LruCacheStoreTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/ComponentRequesterTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/store/DatabaseLocalStoreTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/AppBeagleConfig.kt, backend/sample/spring/src/main/resources/application.properties
=> feat: Improve cache

android/beagle/src/main/java/br/com/zup/beagle/android/components/TabItem.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/core/Constants.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicatorComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleConfig.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
=> refactor: deprecation messages

android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/MainActivity.kt
=> fix: SendRequest action mapper

iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/project.pbxproj, iOS/Example/BeagleDemo/BeagleDemo/AppDelegate.swift, iOS/Example/BeagleDemo/BeagleDemo/Constants/Constants.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/ConditionActionScreen.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/MainScreen.swift, iOS/Schema/BeagleSchema.xcodeproj/project.pbxproj, iOS/Schema/Sources/Action/Types/Condition.swift, iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Schema/Sources/Decoding/ComponentDecoder.swift, iOS/Schema/Sources/Decoding/Tests/__Snapshots__/ComponentDecoderTests/testIfAllActionsAreBeingRegistered.1.txt, iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj, iOS/Sources/Beagle/Sources/Action/Types/Condition.swift, iOS/Sources/Beagle/Sources/Action/Types/Tests/ConditionTests.swift, iOS/Sources/Beagle/Sources/ContextExpression/Expression.swift, iOS/Sources/Beagle/Sources/Setup/Tests/__Snapshots__/BeagleSetupTests/testDefaultDependencies.1.txt
Closes #910
Implements the conditional action.
Implement the conditional action according to the second solution suggested in the following issue: #586.
=> feat: iOS - Conditional Action

android/beagle/src/main/java/br/com/zup/beagle/android/action/AddChildrenAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SetContext.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SubmitForm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/UndefinedAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabBar.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Text.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt
Closes #852 
Create two news functions and adjust all places using the function
=> refactor: add new function to get expression

android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/ServerDrivenActivity.kt, android/beagle/src/main/res/layout/beagle_activity_server_driven.xml, android/beagle/src/main/res/layout/beagle_include_error_server_driven.xml, android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScreenComponentTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt, android/sample/src/main/AndroidManifest.xml, android/sample/src/main/res/layout/activity_main.xml, android/sample/src/main/res/values/styles.xml, backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ImageLocalScreenBuilder.kt
Closes #907
Add support to expression in navigation item
=> feat: add support to bind in menu

iOS/Example/BeagleDemo/BeagleDemo/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Example/BeagleDemo/BeagleDemo/CodeGeneration/Generated/Equality.generated.swift, iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Schema/Sources/CodeGeneration/Generated/Equality.generated.swift, iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Sources/Beagle/CodeGeneration/Generated/Equality.generated.swift, iOS/Sources/Beagle/Sources/Components/TabView+Renderable/TabViewUIComponent.swift, iOS/Sources/Beagle/Sources/Components/TextInput+Renderable/TextInput.swift
=> fix: textInput onBlur

android/sample/src/main/java/br/com/zup/beagle/sample/constants/ColorConstants.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/NavigationFragment.kt, android/sample/src/main/res/menu/menu_navigation_drawer.xml
The firebase application https://t001-2751a.firebaseapp.com/flow/step1.json has been disabled because it is out of date. So I changed the nagevation screen to declarative.
=> refactor: change example navigation screen to declarative

android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/LazyComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabBar.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabItem.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Text.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/Touchable.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/Form.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormInput.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/form/FormSubmit.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ComposeComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Screen.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicatorComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageViewTwo.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/TextInputType.kt
Closes #976 
Public components are not documented beagle android.
Expected: Add javadoc documentation to all public components at the beagle android.
=> feat: add documentation to all public components on the beagle android

android/beagle/src/main/java/br/com/zup/beagle/android/action/AddChildren.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/FormLocalAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/FormRemoteAction.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/FormValidation.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SetContext.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/SubmitForm.kt
Closes #975 
Public actions are not documented beagle android.
Expected: Add javadoc documentation to all public Action at the beagle android.
=> feat: add documentation to all public action on the beagle android

backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ImageScreenBuilder.kt, backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/constants/ImageConstants.kt
- #1016
The tests for the image component were made exclusively for mobile. We also need to support tests for web.
Replaced "mobileOnly" for "both".
=> test: adds support for web to the image test

android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextData.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/GlobalContext.kt, android/beagle/src/main/java/br/com/zup/beagle/android/engine/renderer/RootView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/exception/BeagleApiException.kt, android/beagle/src/main/java/br/com/zup/beagle/android/exception/BeagleException.kt, android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleLogger.kt, android/beagle/src/main/java/br/com/zup/beagle/android/navigation/DeepLinkHandler.kt, android/beagle/src/main/java/br/com/zup/beagle/android/networking/RequestData.kt, android/beagle/src/main/java/br/com/zup/beagle/android/networking/ResponseData.kt, android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleConfig.kt, android/beagle/src/main/java/br/com/zup/beagle/android/store/StoreHandler.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt, android/beagle/src/main/java/br/com/zup/beagle/android/widget/RootView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/widget/ViewConvertable.kt, android/beagle/src/main/java/br/com/zup/beagle/android/widget/WidgetView.kt
Closes #996 
Public classes not documented beagle android.
Expected: Add documentation to the public classes of the context package, exception, logger, navigation, network, configuration, storage, visualization and widget.
=> feat: documentation package at the beagle android

iOS/Example/BeagleDemo/BeagleDemo/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Example/BeagleDemo/BeagleDemo/CodeGeneration/Generated/Equality.generated.swift, iOS/Example/BeagleDemo/BeagleDemo/Screens/ComponentInteractionScreen.swift, iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Schema/Sources/CodeGeneration/Generated/Equality.generated.swift, iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Sources/Beagle/CodeGeneration/Generated/Equality.generated.swift, iOS/Sources/Beagle/Sources/Components/TextInput+Renderable/TextInput.swift
=> Add a way to dismiss the numeric keyboard

android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScreenComponentTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
#1036 
The toolbar does no't  remove the title when the style is center
=> fix: toolbar title

iOS/Example/BeagleDemo/BeagleDemo/Screens/ComponentInteractionScreen.swift, iOS/Schema/Sources/ContextExpression/Expression.swift, iOS/Schema/Sources/ContextExpression/Tests/ExpressionTests.swift, iOS/Schema/Sources/ServerDrivenComponent/TabView/Tests/__Snapshots__/TabViewTests/test_whenDecodingJson_thenItShouldReturnATabView.1.txt, iOS/Schema/Sources/ServerDrivenComponent/WebView/Tests/__Snapshots__/WebViewTests/test_whenDecodingJson_shouldReturnAWebView.1.txt, iOS/Schema/Sources/Widgets/Button/__Snapshots__/ButtonTests/test_whenDecodingJson_thenItShouldReturnAButton.1.txt, iOS/Schema/Sources/Widgets/Container/Tests/__Snapshots__/ContainerTests/test_whenDecodingJson_shouldReturnAContainer.1.txt, iOS/Schema/Sources/Widgets/Image/Tests/__Snapshots__/ImageTests/test_whenDecodingJson_thenItShouldReturnAnImage.1.txt, iOS/Schema/Sources/Widgets/Tests/__Snapshots__/WidgetTests/testParsingOfWidgetWithAllAttributes.1.txt, iOS/Schema/Sources/Widgets/Text/Tests/__Snapshots__/TextTests/test_whenDecodingJson_shouldReturnAText.1.txt, iOS/Schema/Sources/Widgets/TextInput/Tests/__Snapshots__/TextInputTests/test_whenDecodingJson_shouldReturnAText.1.txt, iOS/Schema/Sources/Widgets/WidgetProperties/Style/Style.swift, iOS/Sources/Beagle/Sources/Analytics/Tests/__Snapshots__/AnalyticsTests/testIfDecodingIsSuccessfulForClickEvent.1.txt, iOS/Sources/Beagle/Sources/Analytics/Tests/__Snapshots__/AnalyticsTests/testIfDecodingIsSuccessfulForScreenEvent.1.txt, iOS/Sources/Beagle/Sources/Common/Extensions/StyleBuildersExtension.swift, iOS/Sources/Beagle/Sources/Common/Extensions/Tests/__Snapshots__/StyleBuildersExtensionTests/test_StyleBuilder.1.txt, iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Style/StyleViewConfigurator.swift, iOS/Sources/Beagle/Sources/Renderer/BeagleRenderer.swift
Closes #1061 
A way to show/hide components in the tree using the style property `display`.
=> feat: change Style.display to expression

android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, iOS/Schema/Sources/CodeGeneration/BeagleSchemaGenerated/Style.swift, iOS/Schema/Sources/ServerDrivenComponent/TabBar/TabBarItem+Extension.swift, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/Style.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/StyleSchema.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/FlexSchema.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Size.kt, schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/SizeSchema.kt, schema/schema-ruby-erb/model_generation/Generated/Kotlin/StyleSchema.kt, schema/schema-ruby-erb/model_generation/Generated/KotlinBackend/Style.kt, schema/schema-ruby-erb/model_generation/Models/Layout/style.rb
Update schema with master changes
=> Schema/update components 1.3

android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt, android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/PolymorphicJsonAdapterFactory.java, android/beagle/src/test/java/br/com/zup/beagle/android/action/AlertTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/action/ConfirmTest.kt
Some words was appointed as vulnerability, to improve that, I just change the name, because the dialog.dismiss() contains "log.d" and the log is a vulnerability but the dialog.dismiss not, the same in some comments that have the word "encode"
=> fix: improve vulnerability

android/preview/src/main/java/br/com/zup/beagle/android/preview/PreviewActivity.kt
Change log to toast on PreviewActivity to improve security report
=> fix: remove log on preview activity

iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj, iOS/Tests/AutomatedTests.xcodeproj/xcshareddata/IDETemplateMacros.plist, iOS/Tests/AutomatedTests/AppDelegate.swift, iOS/Tests/AutomatedTests/BeagleConfig.swift, iOS/Tests/AutomatedTestsTests/AutomatedTestsTests.swift, iOS/Tests/AutomatedTestsUITests/AutomatedTestsUITests.swift, iOS/Tests/AutomatedTestsUITests/Elements/ScreenElements.swift, iOS/Tests/AutomatedTestsUITests/Robots/ScreenRobot.swift, iOS/Tests/AutomatedTestsUITests/Steps/ButtonScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/CucumberStepsDefinition.swift, iOS/Tests/AutomatedTestsUITests/Steps/ImageScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/ListViewScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/NavigationActionSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/PageViewScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/ScrollViewScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/SimpleFormScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/TabViewScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Steps/TouchableScreenSteps.swift, iOS/Tests/AutomatedTestsUITests/Utils/TestUtils.swift, iOS/Tests/AutomatedTestsUITests/scrollToExtension.swift
=> fix: header template for automated tests target

.github/workflows/horusec_pr.yml
=> feat: create ci to security

android/automated-tests/src/androidTest/assets/features/TextScreen.feature, android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/elements/ScreenElements.kt, android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/robots/ScreenRobot.kt, android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/Instrumentation.kt, android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/TextScreen.kt, android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/utils/matcher/MatcherExtension.kt, android/automated-tests/src/main/res/values/colors.xml, backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/TextScreenBuilder.kt
https://github.com/ZupIT/beagle/issues/1013
Creates automated tests for text with and without expressions, including:
text
textColor
textAlignment
=> test: add instrumentation test to component Text

iOS/Tests/AutomatedTests.xcodeproj/project.pbxproj, iOS/Tests/AutomatedTests/Config/BeagleConfig.swift, iOS/Tests/AutomatedTests/Config/Logger/BeagleLoggerDefault.swift, iOS/Tests/AutomatedTests/Config/Network/HttpRequestBuilder.swift, iOS/Tests/AutomatedTests/Config/Network/NetworkClientDefault.swift, iOS/Tests/AutomatedTests/CustomNavigationController.swift
#500
Adds a network client default implementation for the functional tests.
=> test: network client default implementation.

.github/workflows/horusec_pr.yml
Added name to Horusec workflow 
=> feat: add name to Horusec workflow

CODEOWNERS
Adds carlossteinzup as an android codeOwner. 
He is not able to approve or do PRs since he is no longer a codeOwner
=> chore: adds carlossteinzup as android codeOwner

android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Screen.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt
#1094 
Add a new attribute called `id` and deprecated attribute `identifier`. 
=> feat: add new attribute id in screen and deprecated field identifier

CODEOWNERS
=> chore: update codeowners 

android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewHolder.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt, android/beagle/src/main/java/br/com/zup/beagle/android/context/tokenizer/TokenFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/ViewFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/list/ListViewHolderTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModelTest.kt, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/list/ListViewActivity.kt, config/detekt-default-config.yml
This PR closes #1125 and updates the `scrollThreshold` property to `scrollEndThreshold`.
=> fix: listView template component with id and context

android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ListViewTest.kt
ListView scroll listener was not working on cucumber tests
=> refactor: changed listview scroll listener

backend/annotation/build.gradle, backend/automated-tests/build.gradle, backend/build.gradle, backend/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt, backend/gradle.properties, backend/gradle/wrapper/gradle-wrapper.properties, backend/kotlin-core/build.gradle, backend/processor-utils/build.gradle, backend/sample/micronaut/build.gradle, backend/sample/spring/build.gradle
None.
Updated all dependencies of the backend library's modules.
=> chore: updated backend modules' dependencies

android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java, android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScrollViewTest.kt
=> fix: adjust scroll horizontal not working correctly

android/beagle/src/main/java/br/com/zup/beagle/android/operation/builtin/array/UnionOperation.kt, android/beagle/src/test/java/br/com/zup/beagle/android/operation/OperationResolverTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/operation/builtin/array/UnionOperationTest.kt
=> feat: Add union context operation

android/beagle/src/test/java/br/com/zup/beagle/ext/UnitValueExtensionsKtTest.kt
=> test: add unit test to unit value extensions

android/beagle/src/main/java/br/com/zup/beagle/ext/WidgetExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/ext/WidgetExtensionsKtTest.kt
=> test: add test unit test to widget extensions

android/jacoco-android.gradle
=> refactor: removed code added to skip classes in jacoco.

android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt, android/internal-processor/build.gradle, android/processor-shared-code/build.gradle, android/processor/build.gradle
fix error between dependencies okio.
=> fix: adjust compile testing to use type test implementation

.github/workflows/horusec_pr.yml
Horusec was reporting for automated-tests package on Backend
=> fix: horusec

android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt, android/jacoco-android.gradle, android/preview/build.gradle, android/preview/src/main/AndroidManifest.xml, android/preview/src/main/java/br/com/zup/beagle/android/preview/PreviewActivity.kt, android/preview/src/test/AndroidManifest.xml, android/preview/src/test/java/br/com/zup/beagle/android/preview/MyBeagleSetup.kt, android/preview/src/test/java/br/com/zup/beagle/android/preview/PreviewActivityTest.kt, android/preview/src/test/resources/robolectric.properties
Actual the `robolectric` not support JUnit 5: https://github.com/robolectric/robolectric/issues/3477, because this the test to activity was write in junit4
=> test: add test to preview activity

android/beagle/src/test/java/br/com/zup/beagle/android/utils/WidgetExtensionsKtTest.kt
refactor WidgetExtensioTest to junit5
=> test: refactor WidgetExtensioTest to junit5

backend/build.gradle, fastlane/Fastfile
Remove the logic publish specific modules in backend
=> fix: publish libraries backend

.github/workflows/ios-pr.yml, codecov.yml, iOS/Sources/Beagle/Beagle.xcodeproj/xcshareddata/xcschemes/All.xcscheme
Fixes wrong coverage report generated for iOS platform.
=> ci: iOS codecov config

iOS/Example/BeagleDemo/BeagleDemo/Screens/MainScreen.swift, iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift, iOS/Sources/Beagle/Sources/Analytics/Tests/__Snapshots__/AnalyticsTests/testIfDecodingIsSuccessfulForClickEvent.1.txt, iOS/Sources/Beagle/Sources/Components/Widget/Button/Button+Extensions.swift, iOS/Sources/Beagle/Sources/Components/Widget/Button/Button.swift, iOS/Sources/Beagle/Sources/Components/Widget/Button/Tests/ButtonTests.swift, iOS/Sources/Beagle/Sources/Components/Widget/Button/Tests/JSON/buttonComponent.json, iOS/Sources/Beagle/Sources/Components/Widget/Button/Tests/__Snapshots__/ButtonTests/test_whenDecodingJson_thenItShouldReturnAButton.1.txt, iOS/Sources/Beagle/Sources/Components/Widget/SimpleForm/Tests/__Snapshots__/SimpleFormTests/test_whenDecodingJson_shouldReturnASimpleForm.1.txt
=> feat: iOS - Disabled button

android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ScreenExtensions.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ScreenExtensionsKtTest.kt
#1261 
Screen.toScreenComponent doesn't map the id from screen to the ScreenComponent
=> fix: screen to component

android/beagle/src/test/java/br/com/zup/beagle/android/engine/renderer/ViewRendererFactoryTest.kt
#1197 
Unit test added to verify that the component was rendered correctly.
=> test: add unit test to ViewRendererFactory

flutter/beagle_components/lib/beagle_button.dart, flutter/beagle_components/lib/default_components.dart, flutter/beagle_components/test/beagle_button_test.dart
#1306
Adds flutter default button. It isn't possible to style the component yet.
=> feat: add flutter default button

android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/AccessibilitySetup.kt, android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt, android/beagle/src/main/java/br/com/zup/beagle/core/Accessibility.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/AccessibilitySetupTest.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/builder/core/AccessibilityBuilder.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/Accessibility.kt
Epic : #1234 
supported for accessibility components on beagle the feature of telling that the component should be treated as a Title(header)
=> feat: add support to accessibility header android and backend

flutter/beagle/lib/setup/beagle_design_system.dart, flutter/beagle_components/lib/beagle_text.dart, flutter/beagle_components/lib/default_components.dart, flutter/beagle_components/test/beagle_text_test.dart, flutter/beagle_components/test/objects_fake/fake_design_system.dart, flutter/sample/lib/app_design_system.dart, flutter/sample/lib/main.dart
#1307 
Add support to style id in the component text
=> feat: add style in component text

android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/AnalyticsProvider.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/AnalyticsService.kt, android/beagle/src/test/java/br/com/zup/beagle/android/logger/BeagleMessageLogsTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/AnalyticsViewModelTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/AnalyticsServiceTest.kt
#745 
This pull request is a fix to remove the queue of analytics 2
=> fix: remove queue on analytics2 android

android/beagle/src/main/java/br/com/zup/beagle/android/utils/StringExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleNavigator.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/ScreenReportFactory.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleNavigatorTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/ScreenReportFactoryTest.kt
This pr is to remove the fun "removeBaseUrl" to allow the analytics have the same behave across the platforms
=> refactor: string extension

flutter/beagle_components/lib/beagle_image.dart
Changed flutter image component to use FutureBuilder.
=> refactor: flutter image component now uses FutureBuilder

android/beagle/src/main/java/br/com/zup/beagle/android/action/AnalyticsAction.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/AddChildren.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Alert.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/AnalyticsAction.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Condition.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Confirm.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Form.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Navigate.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SendRequest.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SetContext.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/SubmitForm.kt
Change the abstract class ActionAnalytics to an interface AnalyticsAction and update the documentation
=> refactor: action analytics

.github/workflows/automated_tests_appium_android.yml, fastlane/automatedTests/appium/android/browserstack/setup_apk_in_browserstack_and_run_android_tests.sh
#1369 
Fixed wrong param names.
=> fix: correct param names in test script

android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/AnalyticsViewModel.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/AnalyticsService.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/DataScreenReport.kt, android/beagle/src/main/java/br/com/zup/beagle/newanalytics/ScreenReportFactory.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleActivityTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleFragmentTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/custom/BeagleViewTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/AnalyticsViewModelTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/AnalyticsServiceTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/DataScreenReportTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/ScreenReportFactoryTest.kt
Signed-off-by: Vinicius Guardieiro Sousa <vinicius.guardieiro@zup.com.br>
Remove unnecessary variables used on analytics after the merge of #1370
=> refactor: remove unnecessary variables

android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/TextInput.kt, iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/TextInputTests.swift, iOS/Sources/Beagle/Sources/Components/Widget/TextInput/TextInput.swift
Closes to #1345.
The deprecated field is hidden.
=> refactor: deprecated field hidden

iOS/Example/BeagleDemo/BeagleDemo/Screens/SimpleForm.swift, iOS/Sources/Beagle/Sources/Action/Types/SubmitForm+Extensions.swift, iOS/Sources/Beagle/Sources/Components/Widget/TextInput/TextInput+Extensions.swift
- Fix a bug related with SubmitForm action and validations, see Appium test @simpleform scenario 02
- Fix some minor ui related problems with TextInput
=> fix: iOS - SubmitForm validations

flutter/beagle/lib/beagle_sdk.dart, flutter/beagle/lib/beagle_widget.dart, flutter/beagle/lib/bridge_impl/beagle_js_engine.dart, flutter/beagle/lib/bridge_impl/beagle_service_js.dart, flutter/beagle/lib/bridge_impl/beagle_view_js.dart, flutter/beagle/lib/bridge_impl/global_context_js.dart, flutter/beagle/lib/bridge_impl/js_runtime_wrapper.dart, flutter/beagle/lib/default/url_builder.dart, flutter/beagle/lib/interface/beagle_service.dart, flutter/beagle/lib/interface/navigation_controller.dart, flutter/beagle/lib/networking/beagle_network_options.dart, flutter/beagle/lib/service_locator.dart, flutter/beagle/lib/utils/enum.dart, flutter/beagle/lib/utils/string_utils.dart, flutter/beagle/test/bridge_impl/beagle_js_engine_test.dart, flutter/beagle/test/bridge_impl/beagle_js_request_message_test.dart, flutter/beagle/test/bridge_impl/beagle_service_js_test.dart, flutter/beagle/test/bridge_impl/beagle_view_js_test.dart, flutter/beagle/test/bridge_impl/js_runtime_wrapper_test.dart, flutter/beagle/test/model/beagle_action_test.dart, flutter/beagle/test/model/response_test.dart, flutter/beagle/test/networking/beagle_network_options_test.dart, flutter/beagle/test/utils/enum_test.dart, flutter/beagle/test/utils/string_utils_test.dart, flutter/beagle_components/lib/beagle_lazy_component.dart
Adds tests to beagle's flutter module.
=> chore: Adds flutter tests

backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/SendRequestScreenBuilder.kt
https://github.com/ZupIT/beagle-web-components/issues/50
It was necessary to change onError and success messages to correct automated web tests.
=> test: fixed sendResquest messages 

backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ButtonScreenBuilder.kt
https://github.com/ZupIT/beagle-web-components/issues/50
After changing the contract from the disabled to enabled attribute, this change is required
=> change button attribute to enabled

android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleConfig.kt, iOS/Sources/Beagle/Sources/Setup/BeagleDependencies.swift
Closes #1277
deprecated field isLoggingEnabled 
=> feat: deprecated field isLoggingEnabled 

android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/android/networking/HttpAdditionalData.kt, android/beagle/src/main/java/br/com/zup/beagle/android/networking/RequestData.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleNavigator.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/networking/HttpAdditionalData.kt
Issue: https://github.com/ZupIT/beagle/issues/1398
Adjust body to accept any data and expression.
=> refactor: adjust body parameter http additional data in route remote

android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/page/PageIndicatorTest.kt
=> fix: adjust crash when passing color in page indicator (#1452)

android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/AnalyticsActionConfigAdapterFactory.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
Closes #1459 
Adjust error in deserialization when passing null in action
=> fix: error when passing analytics null in action

android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/AnalyticsActionConfigAdapterFactory.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
code from 1.6.1 android to master
=> chore: release 1.6.1 android into master

android/beagle/src/main/java/br/com/zup/beagle/android/components/Text.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/BeagleTextViewExtensionsKtTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ListViewTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/TextTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/engine/renderer/ViewRendererFactoryTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/GenerateIdManagerTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/utils/ScreenExtensionsKtTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleActivityTest.kt, android/beagle/src/test/java/br/com/zup/beagle/newanalytics/ActionReportFactoryTest.kt
https://github.com/ZupIT/beagle/pull/1347
adjusting the same problem in the text as in the button
=> fix: adjust instance of text

Gemfile.lock
=> chore: update version of danger

.github/workflows/release-kdocs.yml
A homologation environment was implemented to view and test the documentation generated by Dokka (backend/android) in a controlled environment to be tested before generating a release.
=> fix: add conditional to dokka s3 upload steps

backend/starters/micronaut/src/main/kotlin/br/com/zup/beagle/micronaut/filter/BeagleCacheFilter.kt, backend/starters/micronaut/src/main/kotlin/br/com/zup/beagle/micronaut/filter/BeaglePlatformFilter.kt, backend/starters/micronaut/src/test/kotlin/br/com/zup/beagle/micronaut/filter/BeagleCacheFilterTest.kt
=> fix: micronaut starter stopped hanging when underlying client fails

iOS/Sources/Beagle/Sources/Action/Types/Navigate.swift, iOS/Sources/Beagle/Sources/Action/Types/Tests/NavigateTests.swift, iOS/Sources/Beagle/Sources/Caching/Prefetch/Tests/BeaglePrefetchHelperTests.swift, iOS/Sources/Beagle/Sources/Caching/Prefetch/Tests/__Snapshots__/BeaglePrefetchHelperTests/testNavigationIsPrefetchable.1.txt, iOS/Sources/Beagle/Sources/Logger/Tests/__Snapshots__/BeagleLoggerTests/testLogs.1.txt, iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift, iOS/Sources/Beagle/Sources/Navigation/Tests/BeagleNavigatorTests.swift
=> fix: Expression in actions OpenExternalURL, OpenNativeRoute, PopToView

tests/appium/README.MD
=> feat: link update

iOS/Sources/Beagle/BeagleTests/Logger/BeagleLoggerTests.swift, iOS/Sources/Beagle/BeagleTests/Logger/__Snapshots__/BeagleLoggerTests/testLogs.1.txt, iOS/Sources/Beagle/Sources/Logger/BeagleMessageLogs.swift, iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift
=> fix: popToView error message when route doesnt exist

.github/workflows/horusec_pr.yml
Updating horusec script to remove -F parameter and get project name dynamically in -n parameter.
=> ci: update horusec script

android/beagle/src/main/java/br/com/zup/beagle/android/engine/mapper/FlexMapper.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java, android/beagle/src/test/java/br/com/zup/beagle/android/BaseSoLoaderTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/engine/mapper/FlexMapperTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/custom/BeagleFlexViewTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/view/custom/BeagleViewTest.kt, android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt, android/test/src/main/java/br/com/zup/beagle/test/rules/BeagleComponentsStatement.kt
issue reference: https://github.com/ZupIT/beagle/issues/1437
Update library yoga and use repository from zup
=> feat: add yoga from repository in zup

flutter/beagle/lib/bridge_impl/beagle_js_engine.dart, flutter/javascript-bridge/src/global.d.ts, flutter/javascript-bridge/src/http-client.ts, flutter/javascript-bridge/src/index.ts, flutter/javascript-bridge/src/utils/flutter-js-logger.ts
closes #1403 
Created communication between JS bridge and Flutter code to execute log functionalities.
=> feat: Adds bridge communication for loggers

backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/GridView.kt
add component grid view in backend
=> feat: add component grid view in backend

android/beagle/src/main/java/br/com/zup/beagle/android/components/GridView.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/GridView.kt
add doc in backend and android to component gridview
=> chore: add doc in backend and android to component gridview

Gemfile.lock, fastlane/Fastfile, fastlane/Pluginfile
=> fix: remove codecov to release

backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt, backend/kotlin-core/src/test/kotlin/br/com/zup/beagle/ext/WidgetExtensionsTest.kt
Merging code in master from hotfix
=> chore: merge fix in 1.7.1 to master 

android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt, android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ComponentJsonAdapterFactory.kt
closes #1591 
Remove widgetView inheritance from PageIndicator component:
=> refactor: remove widgetView inheritance from PageIndicator component

android/beagle/src/main/java/br/com/zup/beagle/android/components/GridView.kt
=> fix: adjustment contract grid view

backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/GridView.kt
=> chore: merge fix in master

android/beagle/src/main/java/br/com/zup/beagle/android/context/tokenizer/Token.kt, android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/components/GridViewTest.kt
Closes #1597
create unit test to gridview
=> test: create unit test to gridview

android/android-annotation/build.gradle, android/beagle/build.gradle, android/build.gradle, android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt, android/internal-processor/build.gradle, android/preview/build.gradle, android/processor-shared-code/build.gradle, android/processor/build.gradle, android/sample/build.gradle, android/test/build.gradle
Closes #1613 
Remove libraries not used in project android more.
Update libraries used in the project to the last version available.
=> chore: update dependencies beagle android

iOS/Beagle.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/project.pbxproj, iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj, iOS/Sources/Preview/BeaglePreview.xcodeproj/project.pbxproj
Update Beagle iOS dependencies minimum version:
- YogaKit 1.19.0
- Starscream 4.0.4
- SnapshotTesting 1.9.0
All dependencies was configured with requirement upToNextMajorVersion
=> chore: iOS - Update Beagle Dependencies

android/beagle/consumer-rules.pro
change annotation keepclassmember by keep to avoid future problems in proguard.
=> fix: adjust proguard

android/beagle/src/main/java/br/com/zup/beagle/android/components/refresh/PullToRefresh.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/refresh/PullToRefreshTest.kt
Signed-off-by: Paulo Cesar Meurer <paulo.meurer@zup.com.br>
Adjust PullToRefresh component
=> chore: adjust PullToRefresh

iOS/Sources/Beagle/BeagleTests/ContextExpression/DynamicObjectTests.swift, iOS/Sources/Beagle/Sources/ContextExpression/DynamicObject.swift
Closes #1649
Creates a init for DynamicObject that uses a Encodable input
=> feat: iOS - Adds init from Encodable to DynamicObject

flutter/beagle_components/lib/beagle_container.dart, flutter/beagle_components/lib/beagle_text.dart, flutter/beagle_components/lib/default_components.dart
#1643 
- Implements a separated BeagleContainer component with the event onInit.
- Fixes a bug within the TextComponent (unpredicted null value)
=> feat: flutter: BeagleContainer component

backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/AccessibilityScreenBuilder.kt, flutter/beagle/lib/bridge_impl/beagle_js_engine.dart, flutter/beagle/lib/bridge_impl/renderer_js.dart, flutter/beagle_components/lib/beagle_lazy_component.dart
Remove debug logs used to test js integration
Adjust LazyComponent logger to use BeagleLogger
=> refactor: remove debug logs

iOS/Sources/Beagle/BeagleTests/Renderer/AutoLayoutWrapperTests.swift, iOS/Sources/Beagle/Sources/Renderer/AutoLayoutWrapper.swift
Closes #1668 
Turns off _translatesAutoresizingMaskIntoConstraints_ inside of `AutoLayoutWrapper`
=> feat: iOS - AutoLayoutWrapper enhancement

flutter/beagle/lib/beagle_sdk.dart, flutter/beagle/lib/bridge_impl/beagle_service_js.dart, flutter/beagle/lib/interface/beagle_service.dart, flutter/beagle/lib/service_locator.dart, flutter/beagle/test/bridge_impl/beagle_service_js_test.dart, flutter/sample/lib/main.dart
rename field custom operation to operation
=> refactor: rename field custom operation to operation

flutter/beagle/lib/beagle_sdk.dart, flutter/beagle/lib/default/default_logger.dart, flutter/sample/lib/main.dart
=> feat: add default logger in beagle

backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ImageScreenBuilder.kt
https://github.com/ZupIT/beagle-web-components/issues/57
https://github.com/ZupIT/beagle-web-components/pull/58
Updates builder
=> feat: ImageScreenBuilder update so images show in WEB

flutter/beagle/CHANGELOG.md, flutter/beagle/pubspec.yaml, flutter/beagle_components/CHANGELOG.md, flutter/beagle_components/pubspec.yaml, flutter/readme.md
Added suffix `-alpha` to version name.
=> chore: changed pubspec versions

.github/workflows/automated_tests_appium_android.yml
Related to https://github.com/ZupIT/beagle/pull/1692
=> fix: update dir in CI script

fastlane/automatedTests/start_test_backend.sh
complements https://github.com/ZupIT/beagle/pull/1692
=> fix: update ci script considering new folder

fastlane/automatedTests/start_test_backend.sh
related to https://github.com/ZupIT/beagle/pull/1692
=> fix: wrong dir fix

flutter/beagle/CHANGELOG.md, flutter/beagle/pubspec.yaml, flutter/beagle_components/CHANGELOG.md, flutter/beagle_components/pubspec.yaml, flutter/sample/ios/Podfile.lock, flutter/sample/pubspec.yaml
The `TextInput` component was not rendering.
This PR updates the `yoga_engine` version used by the `beagle` and `beagle_components` with the fix for this bug.
=> fix: update yoga_engine version with new fix

android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/CornerRadiusHelper.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/RoundedImageView.kt, android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/ViewExtensions.kt, android/beagle/src/main/java/br/com/zup/beagle/android/view/ViewFactory.kt, android/beagle/src/main/java/br/com/zup/beagle/core/Style.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt, android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/CornerRadiusHelperTest.kt, android/build.gradle, android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ImageViewFragment.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/Style.kt
Part of #1632 .
This PR implements new properties for `cornerRadius` for styled widgets and for `ImageView` component.
=> feat: improved corner radius

.github/workflows/release-kdocs.yml
Some variable names were changed on AWS and a update was needed on this action
=> feat: Update release-kdocs.yml

.github/workflows/dco-check.yml
Signed-off-by: Hector <hector.custodio@zup.com.br>
Added Action to check for signed commits
=> feat: Adds DCO Action file

iOS/Example/BeagleDemo/BeagleDemo/Screens/PullToRefreshScreen.swift, iOS/Sources/Beagle/BeagleTests/Components/Widget/Image/ImageTests.swift, iOS/Sources/Beagle/BeagleTests/Components/Widget/Text/TextTests.swift, iOS/Sources/Beagle/BeagleTests/Navigation/BeagleNavigatorTests.swift, iOS/Sources/Beagle/Sources/Analytics/Analytics.swift, iOS/Sources/Beagle/Sources/Analytics/Deprecated/DeprecatedAnalytics.swift, iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Screen/Screen.swift, iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ServerDrivenComponent.swift, iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Touchable/Touchable+Extensions.swift, iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Touchable/Touchable.swift, iOS/Sources/Beagle/Sources/Components/Widget/Button/Button.swift, iOS/Sources/Beagle/Sources/Components/Widget/WidgetProperties/Analytics/AnalyticsModels.swift, iOS/Sources/Beagle/Sources/Components/Widget/WidgetProperties/Analytics/Events.swift, iOS/Sources/Beagle/Sources/Setup/BeagleDependencies.swift
#1722 
Deprecate Analytics old implementation
=> feat: iOS - Deprecate Analytics old infrastructure

android/beagle/src/main/kotlin/br/com/zup/beagle/analytics/Analytics.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/analytics/ClickEvent.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/analytics/ScreenAnalytics.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/analytics/ScreenEvent.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/analytics/TouchableAnalytics.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/android/components/Button.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/android/components/Touchable.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/android/components/layout/Screen.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/android/components/layout/ScreenComponent.kt, android/beagle/src/main/kotlin/br/com/zup/beagle/android/setup/BeagleSdk.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/analytics/Analytics.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/analytics/ClickEvent.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/analytics/ScreenAnalytics.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/analytics/ScreenEvent.kt, backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/analytics/TouchableAnalytics.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Screen.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/navigation/Touchable.kt, backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/Button.kt
Don't need it.
Just deprecated old version of analyitics
=> feat: deprecated old version of analytics

.github/workflows/release.yml, fastlane/Fastfile
Adjust the workflow to generate the 1.6.2-android hotfix
The branches names were changed from MASTER to MAIN and this change must be reflected on this branch to generate the hotfix release
=> fix: release.yml for hotfix 1.6.2-android

CONTRIBUTING.md, doc/contributing/dco_rules.md
Signed-off-by: Hector Custódio <hector.custodio@zup.com.br>
Added description of what is expected in each commit when related to DCO signatures
=> feat: updates contributing description

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Updated the README.md and CONTRIBUTING.md. 
- This change has been made in all OS projects, we want to follow a pattern. 
- 
=> Updated readme and contributing guide

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Updated readme and contributing sections. 
=> Fix: Updated Readme and Contributing

README.md
Signed-off-by: carlossteinzup <carlos.stein@zup.com.br>
Adds the community item and Anchor to Forum link
=> updates readme anchor for community

.github/workflows/horusec_pr.yml
Changing the horusec latest version to latest-rc to improve Horusec release process with ZupIT open sources projects being the first users and testers of a release candidate version
=> chore: changing horusec latest version to latest-rc

.github/workflows/license-check.yml
Signed-off-by: Hector Custódio <hector.custodio@zup.com.br>
Updates header license version
=> Updates Header License version

CONTRIBUTING.md, README.md
Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>
- remove the DCO information of the README.md
- Add the Issue section in the CONTRIBUTING.md
Related task: https://app.shortcut.com/devrelopensource/story/227756/atualizar-p%C3%A1gina-de-contributing
=> docs:update readme.md and contributing.md adding an open issues guide

.github/workflows/horusec_pr.yml
Signed-off-by: Hector Custódio <hector.custodio@zup.com.br>
Added horusec token to save reports to horusec web manager 
=> Add Horusec token

README.md
updates readme according to 2.0
=> fix: updates readme according to 2.0
