- codecov.yml
https://docs.codecov.io/docs/carryforward-flags
This option will be help to disable upload all coverages of flags, like now some PR there are showing the error because don't upload the codecov of  some flag, but don't need because.
> Enable carryforward in codecov

- android/beagle/src/main/java/br/com/zup/beagle/utils/ViewExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/utils/ViewGroupExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/view/BeagleView.kt
- android/beagle/src/test/java/br/com/zup/beagle/utils/ViewExtensionsKtTest.kt
**Description**
When the extension function `loadView` was called from a viewgroup with `wrap_content` height, Beagle did not render the content.
**Issue**
Fix #217 
BREAKING CHANGE: The extension function `setBeagleStateChangedListener` has been incorporated into `loadView`
> fix: extension function loadView to viewgroups with wrap_content height

- android/beagle/src/main/java/br/com/zup/beagle/view/BeagleActivity.kt
- android/beagle/src/main/java/br/com/zup/beagle/view/FragmentTransitionAnimation.kt
- android/beagle/src/main/java/br/com/zup/beagle/view/ScreenTransitionAnimation.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/activities/SampleServerDrivenActivity.kt
We don't have a way to customize the fragment transition when new screen navigation happens.
I create a new method that could be overridden from `BeagleActivity` called `fun getScreenTransitionAnimation(): ScreenTransitionAnimation` and now the developer can override this method and customize the fragment transition.
Fixes: #142
> feat: Expose fragment transition API

- backend/processor/src/test/kotlin/br/com/zup/beagle/test/OverrideParentWidgetBindingTest.kt
- backend/processor/src/test/kotlin/br/com/zup/beagle/test/TestCases.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleProcessorExtensions.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleWidgetBindingHandler.kt
- fastlane/Fastfile
Registered widgets which were overriding fields broke the binding generation.
When a Widget overrides a field, in the Binding copy have it also override that field.
> fix: handling binding generation when fields are overridden

- CODEOWNERS
Break backend code owner deadlock.
> fix: add Android CODEOWNERS as backend owners

- backend/processor/src/test/kotlin/br/com/zup/beagle/test/NullableWidgetTest.kt
- backend/processor/src/test/kotlin/br/com/zup/beagle/test/TestCases.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleBindingHandler.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleClass.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleProcessorExtensions.kt
Nullability is currently ignored by binding generation.
Make the whole type nullable when the original is.
> feat: treat nullable fields in binding generation

- android/android-processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/BeagleMoshi.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/AndroidActionJsonAdapterFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleSdk.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/mockdata/CustomAndroidAction.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleClasses.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/RegisteredActionGenerator.kt
Adds registration of custom actions for moshi deserialization by using @RegisterAction
These actions are registered by the user, same as the current registered widgets.
Later this PR We can reuse the logic to generate the boilerplate for the beagle actions
> feat: Adds registration of custom actions for moshi deserialization by using @RegisterAction

- iOS/Schema/BeagleSchema.xcodeproj/project.pbxproj
- iOS/Schema/Sources/Action/Types/FormLocalAction.swift
- iOS/Schema/Sources/Decoding/ComponentDecoder.swift
- iOS/Schema/Sources/Decoding/Tests/ComponentDecoderTests.swift
- iOS/Schema/Sources/Decoding/Tests/__Snapshots__/ComponentDecoderTests/testIfAllActionsAreBeingRegistered.1.txt
- iOS/Schema/Sources/Decoding/Tests/__Snapshots__/ComponentDecoderTests/testIfAllDecodersAreBeingRegistered.1.txt
- iOS/Sources/BeagleUI/BeagleUI.xcodeproj/project.pbxproj
- iOS/Sources/BeagleUI/Sources/Action/LocalFormHandler.swift
- iOS/Sources/BeagleUI/Sources/Action/Tests/LocalFormHandlerTests.swift
- iOS/Sources/BeagleUI/Sources/Action/Types/FormLocalAction.swift
- iOS/Sources/BeagleUI/Sources/Action/Types/Tests/FormLocalActionTests.swift
- iOS/Sources/BeagleUI/Sources/Action/Types/Tests/__Snapshots__/CustomActionTests/test_whenExecuteCustomAction_shouldListenToStateChanges.1.txt
- iOS/Sources/BeagleUI/Sources/Action/Types/Tests/__Snapshots__/FormLocalActionTests/test_whenExecuteFormLocalAction_shouldListenToStateChanges.1.txt
- iOS/Sources/BeagleUI/Sources/Context/FormManager.swift
- iOS/Sources/BeagleUI/Sources/Context/Tests/FormManagerTests.swift
- iOS/Sources/BeagleUI/Sources/Networking/Tests/RepositoryTests.swift
- iOS/Sources/BeagleUI/Sources/Setup/BeagleDependencies.swift
- iOS/Sources/BeagleUI/Sources/Setup/BeagleSetup.swift
- iOS/Sources/BeagleUI/Sources/Setup/Tests/BeagleSetupTests.swift
- iOS/Sources/BeagleUI/Sources/Setup/Tests/__Snapshots__/BeagleSetupTests/testChangedDependencies.1.txt
- iOS/Sources/BeagleUI/Sources/Setup/Tests/__Snapshots__/BeagleSetupTests/testDefaultDependencies.1.txt
Closes #170 
BREAKING CHANGE: allow register actions like components (under the namespace `custom`: `{"_beagleAction_":"custom:myaction"}`)
BREAKING CHANGE: the action `CustomAction` was used to handle the form submit locally, now it is called `FormLocalAction`
> feat: resgister custom actions

- iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/project.pbxproj
Runtime error when running BeagleDemo on a device:
`dyld: Library not loaded: @rpath/BeagleSchema.framework/BeagleSchema`
Add missing BeagleSchema.framework in BeagleDemo target
> fix: missing BeagleSchema.framework in BeagleDemo target

- iOS/Example/BeagleDemo/BeagleDemo/Screens/ComponentInteractionScreen.swift
- iOS/Example/BeagleDemo/BeagleDemo/Screens/MainScreen.swift
- iOS/Example/BeagleDemo/BeagleDemo/Screens/SendRequestScreen.swift
- iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Schema/Sources/ServerDrivenComponent/Form/Form.swift
- iOS/Schema/Sources/ServerDrivenComponent/Form/Tests/JSON/formComponent.json
- iOS/Schema/Sources/ServerDrivenComponent/Form/Tests/__Snapshots__/FormTests/test_whenDecodingJson_thenItShouldReturnAForm.1.txt
- iOS/Schema/Sources/Widgets/Button/Button.swift
- iOS/Schema/Sources/Widgets/Button/Tests/Json/buttonComponent.json
- iOS/Schema/Sources/Widgets/Button/__Snapshots__/ButtonTests/test_whenDecodingJson_thenItShouldReturnAButton.1.txt
- iOS/Sources/BeagleUI/Sources/Action/Types/Tests/FormValidationTests.swift
- iOS/Sources/BeagleUI/Sources/Analytics/Tests/Json/buttonAnalyticsComponent.json
- iOS/Sources/BeagleUI/Sources/Analytics/Tests/__Snapshots__/AnalyticsTests/testIfDecodingIsSuccessfullForClickEvent.1.txt
- iOS/Sources/BeagleUI/Sources/Components/Button+Renderable/Button+Renderable.swift
- iOS/Sources/BeagleUI/Sources/Components/Button+Renderable/Tests/ButtonTests.swift
- iOS/Sources/BeagleUI/Sources/Components/Form+Renderable/Tests/FormTests.swift
- iOS/Sources/BeagleUI/Sources/Context/FormManager.swift
- iOS/Sources/BeagleUI/Sources/Context/Tests/FormManagerTests.swift
- iOS/Sources/BeagleUI/Sources/Logger/Tests/BeagleLoggerTests.swift
- iOS/Sources/BeagleUI/Sources/Logger/Tests/__Snapshots__/BeagleLoggerTests/testLogs.1.txt
- iOS/Sources/BeagleUI/Sources/Renderer/Tests/BeagleScreenViewControllerTests.swift
iOS implementation of `Button` and `Form` changes made in #296 .
BREAKING CHANGE:
- `Button` attribute `action` were renamed to `onPress` and now it's a list of actions.
- `Form` attribute `action` were renamed to `onSubmit` and now it's a list of actions.
> feat: rename Button and Form action

- iOS/Example/BeagleDemo/BeagleDemo/Screens/SendRequestScreen.swift
- iOS/Schema/Sources/Action/Types/Alert.swift
- iOS/Schema/Sources/Action/Types/Confirm.swift
- iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Sources/BeagleUI/Sources/Action/Types/Alert.swift
- iOS/Sources/BeagleUI/Sources/Action/Types/Confirm.swift
**Problem**.  #322 
- iOS application crashed when onPressOk property was not set on Alert and Confirm actions.
**Expected behavior**
- Set a default for those cases. 
**Additional Changes** 
- Title and message are now an Expression<String> instead of String.
> fix: confirm and alert actions

- android/beagle/src/main/java/br/com/zup/beagle/android/networking/HttpClientDefault.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/networking/HttpClientDefaultTest.kt
Empty response body that came with `HTTP 304` from BFF's cache mechanism lead to HTTP client error. 
Check the presence of response body and treat the absence accordingly.
Fixes #300.
> fix: treated empty response body returned with HTTP 304 in Android

- android/beagle/src/main/java/br/com/zup/beagle/android/networking/HttpClientDefault.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/networking/HttpClientDefaultTest.kt
Presence check on Android HTTP client inputstream is failing, leading to empty bodies.
Replace check with EOF exception handling when reading body.
> fix: replaced presence check with EOF exception handling

- iOS/Example/BeagleDemo/BeagleDemo/Screens/ComponentInteractionScreen.swift
- iOS/Schema/Sources/Action/Types/SetContext.swift
- iOS/Schema/Sources/Widgets/TextInput/Tests/JSON/TextInputComponent.json
- iOS/Schema/Sources/Widgets/TextInput/Tests/__Snapshots__/TextInputTests/test_whenDecodingJson_shouldReturnAText.1.txt
- iOS/Sources/BeagleUI/Sources/Action/Types/SetContext.swift
- iOS/Sources/BeagleUI/Sources/Components/WebView+Renderable/WebView+Renderable.swift
Rename context parameter in SetContext to contextId
> fix: SetContext context parameter renamed to contextId

- fastlane/Fastfile
- iOS/Cartfile
- iOS/Cartfile.resolved
- iOS/Schema/BeagleSchema.xcodeproj/project.pbxproj
- iOS/Schema/Cartfile
- iOS/Schema/Sources/Action/Types/Navigate/Tests/Json/pushview.json
- iOS/Schema/Sources/Action/Types/Navigate/Tests/Json/resetapplication.json
- iOS/Schema/Sources/Action/Types/Navigate/Tests/Json/resetstack.json
- iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj
- iOS/Sources/Beagle/Beagle.xcodeproj/xcshareddata/xcschemes/All.xcscheme
- iOS/Sources/Beagle/Beagle.xcodeproj/xcshareddata/xcschemes/Beagle.xcscheme
- iOS/Sources/Beagle/Cartfile
- iOS/Sources/Beagle/Cartfile.resolved
- iOS/Sources/Preview/BeaglePreview.xcodeproj/project.pbxproj
- iOS/Sources/Preview/Cartfile
- iOS/Sources/Preview/Cartfile.resolved
- created an Xcode Scheme named `All` that will be used locally during development and on CI to properly build and test all code
- all targets that use Carthage are now referencing to the same folder that contains all dependencies
- ⚠️ Codecov is still NOT working, but it's better to avoid test failing than coverage drop for now
> chore: new Xcode Scheme called "All" that will build and test everything

- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/page/PageViewTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ScrollViewFragment.kt
**Context**
The `PageView` component in some cases was unable to define its size. Given this behavior, it now occupies the size that the parent view has available.
**Issues**
This PR fix #286 and #287
> fix: pageView size is defined by the parent size

- dokka.gradle
Always start a new release the gradle show warnings about documentation, I disabled to this moment because need to discuss with the team about documentation
> fix: disable warnings about documentation

- backend/framework/src/main/kotlin/br/com/zup/beagle/serialization/jackson/SerializationUtil.kt
Live preview plugin needs all reflection to use class loaders. The annotations used for distinguishing beagle from custom namespaces weren't complying.
Use class loader to reflect on `RegisterAction` and `RegisterWidget`.
> fix: using classloader for annotation checking

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- backend/backend-widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/Image.kt
The Image widget in android and backend had the placeholder on constructor, This allowed to set a placeholder even if the image was local. To solve and look like the IOS, I change the PathType.Remote (on Android) and to have the placeholder and remove the attribute placeholder on Image widget
#418 
No tests was added. I just run the already existing test to ensure that they were functioning normally
> fix: image placeholder on Android and Backend

- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ActionRequestViewModel.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
When onResume is called and BeagleViewModel LiveData onResume is called, it fetch the screen again.
Fixes: #415
> fix: LiveData onActive to not call twice

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
Every time the screen rotation occur, the current context is replaced and consequently the data itself is loss
Fixes #465 
Create a unit test case to not replace the current context.
> fix: context lose its data when screen rotates

- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ContainerTest.kt
- backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/TextScreenBuilder.kt
- common/extended-schema/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt
- common/extended-schema/src/test/kotlin/br/com/zup/beagle/ext/UnitValueExtensionsTest.kt
- common/extended-schema/src/test/kotlin/br/com/zup/beagle/ext/WidgetExtensionsTest.kt
This PR corrects a behavior that a widget received a flex object and another style in a certain order, the previously informed flex was ignored.
> fix: applyStyle method uses flex object

- android/beagle/src/main/java/br/com/zup/beagle/android/cache/CacheManager.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/MapExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/cache/CacheManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/MapExtensionsKtTest.kt
Inside CacheManager every header were not using case sensitive for header names.
Fixes: #479 
Created unit tests to the function that normalize headers map.
> fix: CacheManager normalize headers before use

- android/beagle/src/main/java/br/com/zup/beagle/android/action/UndefinedAction.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
When an unregistered action is found on JSON, actually the application is crashing.
I created the UndefinedAction to be replaced when this kind of JSON is found.
Fixes: #477 
Created unit test scenarios for this case.
> fix: Undefined actions to not crash when trying to deserialize

- iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageView+Renderable.swift
- iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageViewUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/Page+Renderable/Tests/PageViewTests.swift
- iOS/Sources/Beagle/Sources/Components/Page+Renderable/Tests/PageViewUIComponentTests.swift
- iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabView.swift
- iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabViewUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/Tests/TabViewUIComponentTests.swift
- iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
- iOS/Sources/Beagle/Sources/Theme/ThemeTests.swift
The `UIPageViewController` created by the `PageView` were not added as child of the `BeagleController`, making the `navigationController` not available to the `UIPageViewController` children.
It resulted in each page creating a navigation controller for its own.
Fix #444 
`PageViewTests.test_PageViewChildShouldNotCreateNewNavigationController`
> fix: navigation inside PageView

- android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt
Adjust crash when use component Textinput with a default value
fixes #530 
I opened the Sample app and click in disabled form input to check the behaviour continues works.
> fix: adjust crash when use component Textinput with a default value

- android/beagle/build.gradle
- buildSrc/src/main/java/Dependencies.kt
This issue was happen because for minSdk 23+ is necessary import a facebook lib named jni, to solve, I just import this one
#540 
No test was added
> fix: minSdk 23+ crash

- android/beagle/src/main/java/br/com/zup/beagle/android/exception/BeagleApiException.kt
Removed the `internal` keyword.
#547
> fix: remove internal keyword

- backend/framework/src/main/kotlin/br/com/zup/beagle/constants/CorsConstants.kt
- backend/sample/micronaut/src/main/resources/application.properties
- backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/config/CorsConfig.kt
- backend/starters/beagle-micronaut-starter/src/main/kotlin/br/com/zup/beagle/micronaut/filter/BeagleCacheFilter.kt
- backend/starters/beagle-spring-starter/src/main/kotlin/br/com/zup/beagle/spring/filter/BeagleCacheFilter.kt
- backend/starters/beagle-spring-starter/src/test/kotlin/br/com/zup/beagle/spring/filter/BeagleCacheFilterTest.kt
Exposed our custom headers in Spring sample BFF's CORS configuration. 
Only caching the HTTP `GET` method, since the mechanism is not suited for others.
Configured CORS in Micronaut sample BFF.
Fixes #482.
I updated Spring starter's `BeagleCacheFilterTest` with scenarios for the HTTP methods `GET` and non-`GET`.
Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
> fix: coexisting cache filters with CORS

- iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift
- iOS/Sources/Beagle/Sources/Components/Image+Renderable/Tests/ImageTests.swift
The remote image was not canceling the current image request when the value of the expression is changed.
We now store the request token for the current image request and cancel that request when there is a change in the image path expression.
I added the following test to beagle Core:
ImageTests - test_cancelRequestImageRemote
> fix: cancel image request 

- .github/labeler.yml
Updated the name of the old deploy label to its new name CI/CD, because the bot was labeling with the old name.
None.
The fixing commit triggers the labeler, testing that it uses the correct label.
> fix: renamed deploy to CI/CD in labeler settings

- backend/framework/src/main/kotlin/br/com/zup/beagle/cache/BeagleCacheHandler.kt
- backend/framework/src/test/kotlin/br/com/zup/beagle/cache/BeagleCacheHandlerTest.kt
- backend/sample/micronaut/src/main/resources/application.properties
- backend/sample/spring/src/main/resources/application.properties
- backend/starters/beagle-micronaut-starter/src/main/kotlin/br/com/zup/beagle/micronaut/configuration/BeagleCacheConfiguration.kt
- backend/starters/beagle-micronaut-starter/src/main/kotlin/br/com/zup/beagle/micronaut/filter/BeagleCacheFilter.kt
- backend/starters/beagle-micronaut-starter/src/test/kotlin/br/com/zup/beagle/micronaut/Extensions.kt
- backend/starters/beagle-micronaut-starter/src/test/kotlin/br/com/zup/beagle/micronaut/configuration/BeagleCacheConfigurationTest.kt
- backend/starters/beagle-spring-starter/src/main/kotlin/br/com/zup/beagle/spring/configuration/BeagleCacheAutoConfiguration.kt
- backend/starters/beagle-spring-starter/src/test/kotlin/br/com/zup/beagle/spring/configuration/BeagleCacheAutoConfigurationTest.kt
Updated the default value of each starter's included endpoints to be empty.
Closes #446.
I updated the starter's test to consider the new defaults.
BREAKING CHANGE: `beagle.cache.endpoint.include` default is no endpoints now, not all of them, and now uses Kotlin's `Regex` syntax, regardless of framework
> feat: updated backend cache defaults

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
Clear bindings when rebuilding the screen.
https://github.com/ZupIT/beagle/issues/583
Added test to ensure that when adding a context that already exists in `ContextDataManager` all bindings related this context are removed.
> fix: clear bindings from destroyed views

- iOS/Sources/Beagle/Sources/Setup/BeagleDependencies.swift
- iOS/Sources/Beagle/Sources/Setup/Tests/BeagleSetupTests.swift
*Beagle doesn't decode custom components when we don't initialize BeagleDependencies.*
#455 
I Updated `BeagleSetupTests`
> fix: custom components registering

- iOS/Example/BeagleDemo/BeagleDemo/Screens/PageViewScreen.swift
- iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageView+Renderable.swift
Change event name of PageView to be the same of web and android
*Page changing event of PageView must have the same name of the attribute `onPageChange`*
> fix: change event name of PageView

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt
When attempting to Set a context value for a complex object (a list of Genre objects) the SetContext action is not able to serialize a JSON Object and It serializes a String instead
#574 
Create more unit test for this cases.
> fix: Context evaluation for values that is not string

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataTreeHelperTest.kt
Creates a cache for binding data evaluation in `ContextDataManager()`
https://github.com/ZupIT/beagle/issues/535
Ensure that `evaluateContextBindings` saves evaluated data to cache
Ensure that `updateContext` clears cached data
> feat: Add context binding evaluation cache

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
- android/preview/build.gradle
- android/preview/src/main/java/br/com/zup/beagle/android/preview/BeaglePreview.kt
- android/preview/src/main/java/br/com/zup/beagle/android/preview/PreviewActivity.kt
- android/preview/src/test/java/br/com/zup/beagle/android/preview/BeaglePreviewTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/MainActivity.kt
This PR improves and corrects the behavior of the Android LivePreview plugin. Navigation in the plugin was fixed and the dependency used for websocket communication okHttp was replaced by java websocket, removing conflicts with Beagle's host projects.
Fixes #430 and resolves #497 
`beaglePreview_should_use_host_parameter_with_port`,
`beaglePreview_should_use_default_parameter_with_default_port`,
`onClose_should_call_onClose_only_with_remote_is_true`,
`onClose_should_not_call_onClose_when_remote_is_false`,
`onMessage_should_call_onMessage`,
`onError_should_call_onError`
> fix: live preview android plugin dependency and navigation

- backend/starters/micronaut/build.gradle
Fixed test execution of Micronaut stater, adding missing configuration of test platform in its `build.gradle`.
None.
This PR's verification.
> fix: added test platform settings in Micronaut starter

- iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift
- iOS/Sources/Beagle/Sources/Navigation/Tests/BeagleNavigatorTests.swift
- iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
- iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewModel.swift
When navigating to a remote screen Beagle presents a blank screen while the screen is loading.
This PR changes the navigation to fetch screen before navigate, avoiding the blank screen.
Part of #585
Navigation tests updated.
> fix: fetch the screen before the navigation

- .github/workflows/ios-pr.yml
- iOS/Example/BeagleDemo/BeagleDemo/Screens/MainScreen.swift
Changed the iOS PR check action in the CI to cache dependencies from SPM. The intension was to gain performance.
Also removed Carthage action because we don't use it as dependency manager anymore.
#522 
Tested by checking the time used to fetch dependencies and looking if the cache step could get data from cache folder.
> feat: cache iOS dependencies

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
Avoid caching null values. `LruCache` doesn't allow caching null values.
https://github.com/ZupIT/beagle/issues/628
No tests added
> fix: Android context cache

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextValueHandler.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ValueHandler.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
When will evaluateExpression, after get the value of ContextData the value is treated to cast to the specific type
#622 
evaluateExpressionsForContext_should_set_binding_evaluatedExpressions_value_with_int_when_bind_type_is_int
evaluateExpressionsForContext_should_set_binding_evaluatedExpressions_value_with_float_when_bind_type_is_float
evaluateExpressionsForContext_should_set_binding_evaluatedExpressions_value_with_double_when_bind_type_is_double
[DCO]: …
> fix: wrong context data evaluate

- android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/ViewExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
Set the possibility to escape the context expressions of JSON
https://github.com/ZupIT/beagle/issues/536
evaluateAllContext_with_escaping_expressions_should_return_expected_values at ContextDataEvaluationTest
> feat: set possibility of escape expressions

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextPathResolver.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextPathResolverTest.kt
The context Path Resolver class was removing any string value inside a path that matches the context ID String value and not just the value for ID.
Example. If a context ID is set as : user and a path shared the same value partially, like userName , it would remove the user part and attempt to set values or evaluate expression considering "Name" as a biding key.
https://github.com/ZupIT/beagle/issues/670
it_should_not_remove_a_partial_string_value_from_path_that_equals_the_context_id_string_value
Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
[issue …
> fix: ContextPathResolver - Evaluate expression with variable string name value was the same as context id.

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
set first the listener to make sure that the listener variable is not null when the loadView method is called
val view = viewExtensionsViewFactory.makeBeagleView(viewGroup.context).apply {
stateChangedListener = listener
loadView(rootView, screenRequest)
}
https://github.com/ZupIT/beagle/issues/666
No tests were included
The sequence also was changed from test method loadView_should_create_BeagleView_and_call_loadView_with_fragment.
- [X ] No, no existing tests failed, so this is *not* a breaking change.
[DCO]: …
> fix: Android LoadView

- android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java
- android/beagle/src/test/java/br/com/zup/beagle/android/components/WebViewTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/WebViewFragment.kt
Signed-off-by: jenifer-mathias <jenifer.santos@zup.com.br>
This PR corrects a behavior of WebView on Android in which it did not set its own size if the user did not enter a size.
fix #645 
`webViewClient_should_notify_when_page_stops_loading`
> fix: android webview without defined size

- iOS/Example/BeagleDemo/BeagleDemo/AppDelegate.swift
- iOS/Schema/Sources/Decoding/ComponentDecoder.swift
- iOS/Schema/Sources/Decoding/Tests/ComponentDecoderTests.swift
- iOS/Schema/Sources/ServerDrivenComponent/PageIndicator/Indicator/Tests/PageIndicatorTests.swift
- iOS/Sources/Beagle/Sources/Components/Lazy+Renderable/Tests/LazyComponentTests.swift
- iOS/Sources/Beagle/Sources/Components/Page+Renderable/Tests/CustomPageIndicator/CustomPageIndicatorTest.swift
- iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift
- iOS/Sources/Beagle/Sources/Networking/Tests/RepositoryTests.swift
- iOS/Sources/Beagle/Sources/Setup/BeagleSetup.swift
- iOS/Sources/Beagle/Sources/Setup/Tests/BeagleSetupTests.swift
*Components and actions registering does not work when we register before setting the dependencies.*
*I deprecated old registration methods located at BeagleSetup Archive, and now to register components and actions we need to use decoder instance of BeagleDependencies calling:*
```
///Uses struct name automatically as component type name
func register<T: RawComponent>(component type: T.Type)
func register<A: RawAction>(action type: A.Type)
///Uses custom type name 
func register<T: RawComponent>(component type: T.Type, for typeName: String)
func register<A: RawAction>(action type: A.Type, for typeName: String)
```
#656 
I updated the following tests:
```
ComponentDecoderTests
PageIndicatorTests
LazyComponentTests (SwiftLint warnings)
CustomPageIndicatorTests
RepositoryTests …
```
> fix: ios component registering

- backend/build.gradle
- backend/widgets-dsl/gradle.properties
- fastlane/Fastfile
- maven-publish.gradle
Updated backend build scripts to only publish its exclusive modules, skipping shared ones. This is done by checking the id of the artifact to be published.
Fixes #686.
Ran local publish.
> fix: skip publishing shared modules when releasing backend

- android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt
…t class
The WebView component does not process the error screen when it fails, because in the BeagleWebViewClient class it passes the value of the webView context. The solution is to pass the rootView context to the BeagleWebViewClient class.
closes #695 
Tests not changed
> refactor: WebView component does not render error screen when it fails

- danger/ios/Dangerfile
Dangerfile for iOS had a wrong path referencing to the older BeagleUI folder.
No issues were created.
No tests were added or changed for this pull request.
> fix: wrong path in dangerfile for iOS swiftlint

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
We identified one case on expression escaping logic that if we send a string that has double quote and a escape character for this string, when the escaping algorithm run, it removes the escape character.
Example:
`"\"test\"` would be evaluated to `"test"`, removing the escape characters.
Fixes: #694
Created another test case for this problem.
> fix: context escape ignore double quote

- android/beagle/src/main/java/br/com/zup/beagle/android/builder/layout/ScreenComponentBuilder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/builder/ui/ImageBuilder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/builder/ui/TabBarBuilder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/builder/ui/TabViewBuilder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabBar.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabItem.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Screen.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ImagePathTypeJsonAdapterFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/TabBarTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ImageViewFragment.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/LazyComponentFragment.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ListViewFragment.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ScrollViewFragment.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
Renamed PathType to ImagePath, because are inconsistencies between the Android and Backend implementations.
#669
no new tests
BREAKING CHANGE: In Android declarative the pathType now is imagePath
> fix: Refactor PathType to ImagePath

- fastlane/Fastfile
There is a problem when pushing Pods with dependencies within themselves version due to how frequently CocoaPods trunk refreshes its content. Since `Beagle.spec` depends on `BeagleSchema.spec`, we are exposed to this problem, and so by using the `synchronous` flag, we can try to avoid it.
> ci: iOS when releasing Pods, tries to avoid eventual consistency problem

- android/beagle/src/main/java/br/com/zup/beagle/android/cache/CacheManager.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/ComponentRequester.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/cache/CacheManagerTest.kt
Changed `CacheManager` to only push disk cache to memory when API returns 304 status code.
https://github.com/ZupIT/beagle/issues/716
Adjusted CacheManager tests
> fix: Avoid showing cold cache from disk

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/GlobalContext.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/GlobalContextTest.kt
We have been requested to change the parameters position at the GlobalContext.set constructor in order to list the VALUE parameter first since it is a mandatory parameter and place the PATH parameter second since it is a OPTIONAL parameter.
No issue has been created for this. We have changed that following replies from the documentation and in order to keep in balance with WEB constructors.
Changed the parameters position at tests
set_should_not_override_other_paths_in_global_context_root
updateContext_should_call_global_context_when_id_is_global
Did any tests fail when you ran them? Please read [Handling breaking …
> refactor: GlobalContext - Changed the parameters position in GlobalContext.set constructor

- android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleSdk.kt
We need a way for the user to configure SoLoader in test mode if its using robolectric to avoid the NullPointerException
> fix: Adds method to configure SoLoader in test mode, this is needed to use beagle with robolectric

- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
When doing two or more consecutive calls to `loadView` to the same url, beagle was not notifying loadStart event to the second call.
According to conversation with @tuliopereirazup we choose to remove the url fetching queue behavior due to this behavior is not present on iOS platform.
https://github.com/ZupIT/beagle/issues/726
No new tests added
> fix: load view error with successive calls to same url

- .github/workflows/release.yml
- fastlane/Fastfile
- we were not being able to generate a proper release notes due to a config on GitHub workflow that was only fetching the current commit, and not the whole git history
- when inside a hotfix branch, we were getting the last released **hotfix** tag, and not the last released tag
> ci: fix problem of generating release notes

- android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/action/SendRequestTest.kt
The data attribute content on the SendRequest class is not being converted into a JSON Object when sent in a RequestActionMethod.POST via declarative view on the FRONTEND.
It is being turned into a regular String.
- I have fixed this by adding the `normalizeContextValue()` treatment at the data sent on the SendRequest class.
https://github.com/ZupIT/beagle/issues/737
Data sent should be an JSON object
> fix: SendRequest for Android Declarative.

- android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt
Our WebView component is ignoring SSL errors and letting users navigate to unknown hosts that could open doors to an attack.
> fix: WebView component should not handle ssl errors

- android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/BindAdapterFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/mockdata/ComponentBinding.kt
When a bind attribute is type of List or Map, our deserialiser is not handling and crashing.
Example:
`val map: Bind<Map<String, String>>` or `val list: Bind<List<String>>`
Create more unit test to make sure this will nor occur again.
> fix: Bind deserialization for Map and List

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
After retrieves the value from the global context and updating the value on the same screen, you cannot update the value.
closes #738 
the ContextDataManagerTest class was modified to validate that the cache is being cleared when the global context has an update
> fix: Global context does not clear cache

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
Fix image to show placeholder
#729 
Fix a mock on setup, remove the build_should_call_setImageBitmap_reloadNetworkImageView_when_component_has_not_flex() and add build_should_setPlaceholder_when_imagePath_is_remote_and_placeholder_is_declared()
*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. …
> fix: image placeholder on android

- android/beagle/src/main/java/br/com/zup/beagle/android/action/OnInitableComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabItem.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/form/Form.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/form/SimpleForm.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Screen.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageViewTwo.kt
- schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/AccessibilityComponent.kt
- schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/MultiChildComponent.kt
- schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/SingleChildComponent.kt
- schema/kotlin-core/src/main/kotlin/br/com/zup/beagle/core/StyleComponent.kt
For the `ListView` component to be able to manage and browse the `template`'s widget tree in search of its `id`s and `onInit` actions, it is necessary to add markup interfaces with such pre-defined properties. For more details on the implementation of the `ListView` component, access this [epic](https://github.com/ZupIT/beagle/issues/210).
> refactor: added interfaces for components with child, children and onInit properties

- android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/activities/SampleServerDrivenActivity.kt
This pr creates a method for the user check at any moment if the beagle activity has any screen loaded.
https://github.com/ZupIT/beagle/issues/788
> feat: Adds method to check if the activity have a server driven screen loaded

- android/beagle/src/main/java/br/com/zup/beagle/android/components/LazyComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabBar.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabItem.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/form/SimpleForm.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ComposeComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/Container.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScreenComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageViewTwo.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextComponentHandler.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/engine/renderer/ViewRenderer.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/ViewFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleView.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/BaseTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/LazyComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/form/SimpleFormTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ComposeComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ContainerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScreenComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScrollViewTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextComponentHandlerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/engine/renderer/AbstractViewRendererTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/WidgetExtensionsKtTest.kt
This PR changes the parameters of `BeagleFlexView` and `BeagleView` so that instead of receiving an attribute of type `context`, they receive `rootView`. This way the code is a little cleaner and these classes will have reference to the `viewModel`. It is worth mentioning that these changes are necessary for the implementation of the `ListView` with context.
> refactor: added rootView to BeagleFlexView as parameter on Android

- android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/navigation/DeepLinkHandler.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleNavigator.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/action/NavigateTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleNavigatorTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/AppDeepLinkHandler.kt
Add parameter `rootView` in deep link handler, this will help the user want to open some specific activity.
```
class AppDeepLinkHandler : DeepLinkHandler {
override fun getDeepLinkIntent(rootView: RootView,
path: String,
data: Map<String, String>?,
shouldResetApplication: Boolean): Intent {
return if (path.contains("detail")) {
Intent(rootView.getContext(), MainActivity::class.java)
.putExtra("id", data!!["id"])
} else {
Intent(path)
}
}
```
Closes #770 
Updated the tests that were created.
add in the body of commit:
BREAKING CHANGE: AppDeepLinkHandler add new parameter RootView in function getDeepLinkIntent
Did any …
> feat: add parameter rootview in deeplinkhandler

- iOS/Sources/Beagle/Sources/ContextExpression/Tests/UIView+ContextTests.swift
- iOS/Sources/Beagle/Sources/ContextExpression/UIView+Context.swift
The extension method `UIView.configBinding(for:completion:)` retains the view and there is no way to release it.
- create a view
- call `view.configBinding(for:completion:)`
- create a weak reference to the view
- release the strong reference to the view
- check if the weak reference points to nil
See `UIViewContextTests.testConfigBindingShouldNotRetainTheView`
> fix: configBinding retain cycle

- android/beagle/src/main/java/br/com/zup/beagle/android/engine/renderer/ViewRenderer.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt
if some error happens when generating id, generate automatically id without using view model.
> fix: generate id if some error happen

- iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
- iOS/Sources/Beagle/Sources/Renderer/Tests/BeagleScreenViewControllerTests.swift
In `execute(actions:contextId:contextValue:origin:)` the view configured with the implicit context must be the origin view. Before it was configured for the root view and in most cases it works because the context was resolved too, even at the root.
I added `testExecuteActions` for check this specific scenario.
> fix: iOS - Execute actions with implicit context

- iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
#788, #818 
Creates a function for the user check at any moment if the view controller has any screen loaded.
> fix: iOS - Adds a func to check if the controller have a server driven screen loaded

- iOS/Sources/Beagle/Sources/Logger/BeagleMessageLogs.swift
We can't use `NetworkRequest` and `NetworkResponse` inside log because their init methods are not public.
Now we can log events like this:
`dependencies.logger.log(Log.network(Log.Network.httpResponse(response: .init(data: nil, response: nil))))`
` dependencies.logger.log(Log.network(Log.Network.httpRequest(request: .init(url: nil))))`
> fix: making init in network structs inside log public

- android/beagle/src/main/java/br/com/zup/beagle/android/context/tokenizer/TokenInterpreter.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/tokenizer/TokenParserTest.kt
When parsing expressions on Android, all characters that are different from `.` were excluded. Whit that, when the expression made reference to an index of a list, this path was ignored as well. This PR adds as allowed characters in addition to `.` the `[` and `]`.
> fix: parse expression with index path

- android/beagle/src/main/java/br/com/zup/beagle/android/components/TabBar.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageViewTwo.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/TabBarTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/page/PageViewTwoTest.kt
#395 # Description and Example
When I update the context the `TabBar` and `PageView` they not updated:
Adjust the correct reference of the view to the context can be notified:
> fix: update context in tabbar and pageview

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/WidgetExtensionsKtTest.kt
Change the place where the call method `viewCreated` now this code will work better to async view because I only put the view created when someone rotate the screen.
> fix: improve generate id to async view

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
Some developers to test the beagle use only a simple load view:
but with the new version, the method broke, I created the new methods where you don't need to pass the listener.
> fix: adjust load view

- Beagle.podspec
- BeagleSchema.podspec
- fastlane/Fastfile
When inside a _hotfix_ flow, we create a tag like `1.2.1-iOS` to indicate that it's a hotfix just for iOS, but we don't want our users to handle that `-iOS` suffix on their dependencies, we want them to just see and use version `1.2.1`. For this, it was necessary to change `version` and `tag` parameters inside a `.podspec`, so the former gets just the numbers and the latter stays with the suffix.
I also made some minor refactoring inside `Fastfile`.
> ci: iOS update podspec version and tag independently so hotfix works

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/JsonReaderExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
This PR fixes the bug when Beagle deserialized an array where its children were objects, and these were mistakenly converted to strings.
> fix: objects inside arrays are converted to String

- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
This PR changes the assertions made in the Moshi test class. The tests in JsonObject and JsonArray are more assertive because in addition to validating the type, we validate the values of each received value.
> fix: assert made in moshi tests

- android/internal-processor/src/main/java/br/com/zup/beagle/android/internal/processor/InternalWidgetFactoryProcessor.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterActionProcessor.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterWidgetProcessor.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleSetupRegisteredWidgetGenerator.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/RegisteredActionGenerator.kt
fixes: #673 
As we are generating the boilerplate for widgets and actions registration, now developers can create their own BeagleSetup class to control how @BeagleComponent classes will be instantiated, using dependency injection or not and use these two generated class to return the registration of widget and actions.
> feat: Generating extra class for Widget and Actions registration

- android/beagle/src/main/java/br/com/zup/beagle/android/context/Bind.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextExpressionReplacer.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/BindAdapterFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt
Closes: #892
When these given values is set as a string or expression, we are evaluating to null.
Case 1: When context value is type of string and has a closing curly brace. Ex.: "test } @{context}"
Case 2: When the root of SetContext is a JSONArray or JSONObject. Ex.: {"key": "value"}
> fix: Expression is evaluating to null for specific cases

- android/android-annotation/src/main/kotlin/br/com/zup/beagle/android/annotation/RegisterBeagleAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/BeagleMoshi.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/defaults/CharSequenceAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/defaults/MoshiArrayListJsonAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/defaults/PairAdapterFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/BeagleGenericAdapterFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/BeagleTypeAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/ParameterizedTypeFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/TypeAdapterResolver.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/setup/BeagleSdk.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/BaseTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/mockdata/PersonAdapterFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/mockdata/TypeAdapterResolverImpl.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleAnnotationProcessor.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
- android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/adapters/PersonAdapter.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/widgets/Input.kt
- android/sample/src/test/java/br/com/zup/beagle/sample/BeagleSetupTest.kt
- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/BeagleClasses.kt
Closes #715 
This fix makes Beagle able to register custom adapters do help `Moshi` serialize/deserialize non POJO data
> feat: add support to user register adapter to moshi

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
Fixes: #904
Whenever loadView is called, we should clear all views from the ViewGroup before loading the components.
> fix: call removeAllViews before addView

- iOS/Example/BeagleDemo/BeagleDemo/Screens/SendRequestScreen.swift
- iOS/Schema/Sources/Action/Types/SendRequest.swift
- iOS/Schema/Sources/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Sources/Beagle/Sources/Action/Types/SendRequest.swift
- iOS/Sources/Beagle/Sources/Action/Types/Tests/SendRequestTests.swift
- Altered the method and headers parameters to be bindable fields.
> fix: send request bindable fields

- iOS/Schema/Sources/Action/Types/Navigate/Navigate.swift
- iOS/Schema/Sources/ContextExpression/Expression.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression.swift
- The new navigate constructor allows strings but doesn't allow constants with strings, this is causing old applications to break. 
> fix: adding deprecated constructor to navigate

- android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/InputTextTest.kt
Closes #936 
In some applications, the component `TextInput` didn't has focusing, set programmatically the possible to component has a focus
> fix: add focus in component text input

- iOS/Example/BeagleDemo/BeagleDemo/Screens/OperationsScreen.swift
- iOS/Sources/Beagle/Sources/Components/TabView+Renderable/TabViewUIComponent.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Tests/UIView+ContextTests.swift
- iOS/Sources/Beagle/Sources/ContextExpression/UIView+Context.swift
Related Issues
Closes #906
Binding with multiple expression was not working correctly when using cache 
> fix: iOS - multiple expression binding when using cache

- android/beagle/src/test/java/br/com/zup/beagle/android/action/FormValidationTest.kt
#678 
the command jacocoTestReport was failing on Windows, FormValidationTest had an every that was given a result to extension fun (View.beagleComponent), this extension fun was not used on FormValidation
> fix: jacoco error on windows

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
Closes #907 
Actually, the new fields attribute was created to help more people and the actual constructor doesn't need to be deprecated.
> refactor: remove deprecated from constructor

- android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/layout/ScrollView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/layout/ScrollViewTest.kt
Closes #929 
When putting some views inside the scroll view with some layout height change the view not recalculate, create the strategy to inside the scroll view always layout change put the height to auto and dirty all the views.
> fix: resize view when inside the scroll layout

- common/processor-utils/src/main/kotlin/br/com/zup/beagle/compiler/KotlinPoetExtensions.kt
Closes #964
`extendsFromClass` should check all the class inheritance rather than just checking the first class of the inheritance.
> fix: make extendsFromClass check all super classes in hierarchy

- android/beagle/src/main/java/br/com/zup/beagle/android/data/ComponentRequester.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt
#973 
Crash app when startActivity is called using a JSON without a ScreenComponent, this happen because in the method onResume on BeagleActivity, before call the fetch was doing a cast to ScreenComponent
> fix: app crash when use a JSON without ScreenComponent on startActivity

- iOS/Sources/Beagle/Sources/Action/Types/SetContext.swift
- iOS/Sources/Beagle/Sources/ContextExpression/DynamicObject.swift
- iOS/Sources/Beagle/Sources/ContextExpression/GlobalContext.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Tests/DynamicObjectTests.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Tests/__Snapshots__/DynamicObjectTests/testSetObjectWithVariousPaths.1.json
Closes #986 
Fixes a wrong behaviour in set(value: with path:) method in DynamicObject. Example:
```json
{
"d": [
{
"name": "John", 
"code": "123"
}
]
}
set "UPDATED" with path "d[0].name" returns
{
"d": [
{
"name": "UPDATED"
}
]
}
expected was
{
"d": [
{
"name": "UPDATED",
"code": "123"
}
]
}
```
> fix: iOS DynamicObject set(value: with path:) behaviour

- android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt
Closes #839 
Create a interface to communicate between BeagleFragment and BeagleActivity to send event when fragment is created, this way we can resend this event in BeagleActivity through onServerDrivenContainerStateChanged callback and avoid user to animate toolbar in wrong states.
> fix: fragment transition toolbar glitch

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ColorUtils.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ColorUtilsTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ImageViewFragment.kt
Closes #1031 
This PR fixes the error when colors in the RGB format were not parsed in the Beagle in APIs 29 and bellow.
> fix: parse color when is RGB size

- android/automated-tests/src/androidTest/assets/features/SimpleFormScreen.feature
- android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/GenericSteps.kt
- android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/ImageScreenSteps.kt
Fix image test and simple form test, changing the value on Then of ImageScreenSteps and create a scrollTo on simpleform to scroll to button before click
> fix: image and simple form test

- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/form/SimpleForm.kt
Closes #1038 
SimpleForm component have the context attribute, however all components must inherit from contextComponent to override context attribute
Expected: All components that have the context attribute, have to inherit from ContextComponents to override context attribute
> refactor: simpleform inherit contextComponent

- iOS/Schema/BeagleSchema.xcodeproj/project.pbxproj
- iOS/Schema/Sources/Action/Types/AddChildren.swift
- iOS/Schema/Sources/Action/Types/Tests/AddChildrenTests.swift
- iOS/Schema/Sources/Action/Types/Tests/__Snapshots__/AddChildrenTests/testDecodingAddChildren.1.txt
- iOS/Schema/Sources/Action/Types/Tests/__Snapshots__/AddChildrenTests/testDecodingAddChildrenWithDefaultMode.1.txt
Fixes #1048 
Fix conformance in enum `AddChildren.Mode`
> fix: iOS - addChildren schema conformance

- android/beagle/src/main/java/br/com/zup/beagle/android/networking/HttpClientDefault.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/networking/HttpClientDefaultTest.kt
this code crashing the application: Container(
onInit = listOf(SendRequest(url = "http://localhost:8081/loan/25/simulate",
method = RequestActionMethod.POST,
data = "test"))) 
add in requestbody try catch to handle exception
> fix: http client crash when set body and request fail

- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextBinding.kt
https://github.com/ZupIT/beagle/issues/1047
When starting the beagleconfig with Cache (enabled = false, maxAge = 0), it started ContextBinding using the value 0 for the stack size of your LRU cache. Soon, it threw an exception: IllegalArgumentException ("maxSize <= 0").
> fix: maxSize cache of ContextBinding

- iOS/Schema/Sources/ContextExpression/Parser.swift
- iOS/Schema/Sources/ContextExpression/Tests/ExpressionTests.swift
- iOS/Schema/Sources/ContextExpression/Tests/PathTests.swift
- iOS/Schema/Sources/ContextExpression/Tests/__Snapshots__/ExpressionTests/testValidMultipleExpressions.1.txt
- iOS/Schema/Sources/ContextExpression/Tests/__Snapshots__/ExpressionTests/testValidSingleExpression.1.txt
Fixes #1059 
Fixes a problem with path parser when a path key starts with digit. Sample: "2"
> fix: iOS - Fix Path Parser

- .github/workflows/release.yml
- fastlane/Fastfile
This enables the CI to generate releases from any branch(not only master).
> ci: changed workflow to enable release from any branch

- android/beagle/src/main/java/br/com/zup/beagle/android/cache/CacheManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/cache/CacheManagerTest.kt
When cache enabled and the handle is null the app crashing.
Adjust this logic and create unit test.
> fix: adjust crash in cache manager

- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Alert.kt
closes #1108 
Added default value for alert's parameter title
> fix: alert parameter's default value

- iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
- iOS/Schema/Sources/ServerDrivenComponent/ListView/ListView.swift
- iOS/Schema/Sources/ServerDrivenComponent/ListView/Tests/ListViewTests.swift
- iOS/Sources/Beagle/Sources/Components/ListView+Renderable/ListView+Renderable.swift
- iOS/Sources/Beagle/Sources/Components/ListView+Renderable/ListViewUIComponent.swift
Fix ListView property to match other platforms.
> fix: rename ListView property scrollThreshold to scrollEndThreshold

- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/OnInitiableComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextActionExecutor.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/OnInitViewModel.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/OnInitiableComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextActionExecutorTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/OnInitViewModelTest.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/ListView.kt
This PR adds the `OnInitViewModel` class to handle the execution status of the `onInit` actions of the `OnInitiableComponent`s when the device is rotated.
> feat: add OnInitViewModel to handle onInit status on Android

- android/beagle/src/main/java/br/com/zup/beagle/android/components/OnInitiableComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListItem.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewHolder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewModels.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/GenerateIdManager.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/OnInitViewModel.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/OnInitiableComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/list/ListViewHolderTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/GenerateIdManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/OnInitViewModelTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModelTest.kt
- android/build.gradle
This PR fixes the behavior where onInit actions were re-executed when the device was rotated. OnInit's status update logic was also centralized to `OnInitiableComponentImpl`, in addition to simplifying the `ListAdapter`.
> feat: handle config changes for onInit calls

- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
When listview is empty and has a non null scrollEndThreshold, onScrollEnd is not being called.
> fix: android listview scroll threshold calculation

- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewHolder.kt
When an embedded ListView does not have ContextData neither a BFF id, system crashes because all ListViews in beagle android must have an id.
> fix: Android embedded listview without id

- iOS/Beagle.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/project.pbxproj
- iOS/Example/BeagleDemo/BeagleDemo.xcodeproj/xcshareddata/xcschemes/BeagleDemo.xcscheme
- iOS/Libraries/YogaKit/YogaKit.xcodeproj/project.pbxproj
- iOS/Libraries/YogaKit/YogaKit.xcodeproj/xcshareddata/xcschemes/YogaKit.xcscheme
- iOS/Schema/BeagleSchema.xcodeproj/xcshareddata/xcschemes/Schema.xcscheme
- iOS/Schema/Sources/ServerDrivenComponent/ListView/ListView.swift
- iOS/Schema/Sources/ServerDrivenComponent/PageView/PageView.swift
- iOS/Schema/Sources/ServerDrivenComponent/Scroll/ScrollView.swift
- iOS/Schema/Sources/ServerDrivenComponent/TabView/TabView.swift
- iOS/Schema/Sources/Widgets/Container/Container.swift
- iOS/Schema/Sources/Widgets/SimpleForm/SimpleForm.swift
- iOS/Sources/Beagle/Beagle.xcodeproj/xcshareddata/xcschemes/All.xcscheme
- iOS/Sources/Beagle/Beagle.xcodeproj/xcshareddata/xcschemes/Beagle.xcscheme
- iOS/Sources/Preview/BeaglePreview.xcodeproj/project.pbxproj
- iOS/Sources/Preview/BeaglePreview.xcodeproj/xcshareddata/xcschemes/BeaglePreview.xcscheme
- iOS/Tests/AutomatedTests.xcodeproj/xcshareddata/xcschemes/AutomatedTests.xcscheme
- iOS/Tests/AutomatedTests.xcodeproj/xcshareddata/xcschemes/AutomatedTestsUITests.xcscheme
We added a `#if swift(<5.3)` compiler condition in some `init` that used **Function Builders**, because in swift _5.3_ we don't need to have `ChildrenBuilder` _and_ `ChildBuilder`, now with only `ChildrenBuilder` we can handle both _single_ parameter and _multiple_ parameters.
So, to still make our code compatible with previous swift versions, we will include that if statement in our code.
Closes #931 
> fix: Xcode 12 compiling issues

- iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
- iOS/Sources/Beagle/Sources/ContextExpression/OperationsProvider.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Tests/OperationEvaluation/OperationArrayEvaluationTests.swift
- iOS/Sources/Beagle/Sources/Setup/Tests/__Snapshots__/BeagleSetupTests/testDefaultDependencies.1.txt
#503 
The array _union_ operation was missing on iOS. 
```typescript
union(...arrays: any[][]) => any[]
```
> feat: iOS - Union Operation

- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/ListView.kt
Adds useParentScroll property to backend listview contract. This property is used only on web
> fix: Add useParentScroll property to ListView

- android/beagle/src/main/java/br/com/zup/beagle/android/components/OnInitiableComponent.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewHolder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewExtensions.kt
- android/beagle/src/main/res/values/ids.xml
- android/beagle/src/test/java/br/com/zup/beagle/android/components/OnInitiableComponentTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/list/ListViewHolderTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ViewExtensionsKtTest.kt
Given a listView with a template that has a component with onInit actions and no id is setted on BFF to this component, then the onInit actions will be executed only for the first item on listView. 
> fix: android listview oninit actions not been called for template items

- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
This PR changes listView scroll threshold calculation. Now it uses the real scroll distance.
> feat: Change android listView scroll threshold calculation

- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewHolder.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/GenerateIdManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/GenerateIdManagerTest.kt
Android listView was not recovering its internal views ids correctly when device screen was rotated.
> fix: Android listView id management

- iOS/Schema/Sources/Action/Types/Navigate/Navigate.swift
- iOS/Schema/Sources/Action/Types/Navigate/Tests/NavigateTests.swift
- iOS/Sources/Beagle/Sources/Action/Types/Navigate.swift
- iOS/Sources/Beagle/Sources/Caching/Prefetch/Tests/__Snapshots__/BeaglePrefetchHelperTests/testNavigationIsPrefetchable.1.txt
- iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift
Closes #1225 
Add the property controllerId to action resetApplication. It is used to customize the navigation controller.
> fix: add controllerId to action resetApplication

- android/automated-tests/src/androidTest/assets/features/ListView.feature
- android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataManager.kt
When a view with context was being restored after getting recycled, the context binding reference was being incorrectly changed due to call to View.setContextData().
> fix: android listview context reference

- iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift
Avoids console execution warning log *[framework] CUICatalog: Invalid asset name supplied: ''*
Closes ZupIT#1242
> fix: iOS - aborting local image asset load for empty mobileId

- iOS/Sources/Beagle/Sources/Action/Types/Navigate.swift
- iOS/Sources/Beagle/Sources/Action/Types/Tests/NavigateTests.swift
Closes #1239
See description at #1239 and test `testDecodingResetApplication`
> fix: add missing field controllerId when decoding action resetApplication

- android/beagle/build.gradle
- android/build.gradle
This PR adds support for generating the javadoc md files supported on hugo.
> feat: Adds support for generation of dokka documentation to hugo md files

- flutter/beagle/lib/utils/color_utils.dart
- flutter/beagle_components/lib/beagle_text.dart
- flutter/beagle_components/lib/default_components.dart
- flutter/beagle_components/test/beagle_text_test.dart
#1306
Adds flutter default text component. It isn't possible to style the component yet.
> feat: add flutter default text component

- iOS/Example/BeagleDemo/BeagleDemo/Screens/TabBarScreen.swift
- iOS/Sources/Beagle/Sources/Components/Widget/Tests/JSON/widgetWithAllAttributes.json
- iOS/Sources/Beagle/Sources/Components/Widget/Tests/__Snapshots__/WidgetTests/testParsingOfWidgetWithAllAttributes.1.txt
- iOS/Sources/Beagle/Sources/Components/Widget/WidgetProperties/Accessibility/Accessibility.swift
- iOS/Sources/Beagle/Sources/Components/Widget/WidgetProperties/Accessibility/AccessibilityTests.swift
- iOS/Sources/Beagle/Sources/Renderer/ViewConfigurator.swift
Epic: #1234 
Support for accessibility header on components from beagle, it tells that a given component should be treated as a Title(header).
Example: Text("Title 1") with isHeader as true, would be said in VoiceOver as "Title 1, header" 
> feat: accessibility header 

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/ViewFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ButtonTest.kt
Closes #1338
when the button didn’t have bff style, it was different from the standard
> fix: adjust appearance of button when there's no style

- flutter/beagle_components/lib/beagle_page_indicator.dart
- flutter/beagle_components/lib/beagle_touchable.dart
- flutter/beagle_components/lib/default_components.dart
- flutter/beagle_components/test/beagle_page_indicator_test.dart
- flutter/beagle_components/test/beagle_touchable_test.dart
- flutter/sample/lib/beagle_sample_screen.dart
- flutter/sample/lib/main.dart
#1306
Adds flutter default page indicator and touchable components.
> feat: add flutter default page indicator and touchable components

- flutter/beagle_components/lib/beagle_webview.dart
- flutter/beagle_components/lib/default_components.dart
- flutter/beagle_components/pubspec.yaml
- flutter/beagle_components/test/beagle_webview_test.dart
- flutter/sample/lib/main.dart
#1306
Adds flutter default WebView component.
It uses flutter team webview package: https://pub.dev/packages/webview_flutter
> feat: Add flutter default WebView component

- android/beagle/src/main/java/br/com/zup/beagle/newanalytics/ActionReportFactory.kt
- android/beagle/src/main/java/br/com/zup/beagle/newanalytics/AnalyticsRecord.kt
- android/beagle/src/test/java/br/com/zup/beagle/newanalytics/ActionReportFactoryTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/newanalytics/ScreenReportFactoryTest.kt
#745 
This pr is a change on AnalyticsRecord so that the json generated by the platforms are the same.
> refactor: Change the AnalyticsRecord structure

- iOS/Sources/Beagle/Sources/Analytics/Service/RecordFactory.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/Tests/ActionRecordFactoryTests.swift
#745
- rounds timestamp to be equal to other platforms
- fix when global config enabled and action enabled(nil)
> fix: timestamp and beahvior when both global config and action config are enabled

- iOS/Example/BeagleDemo/BeagleDemo/DesignSystem/GenerationTests/Protocols.swift
- iOS/Example/BeagleDemo/BeagleDemo/Screens/GlobalContextScreen.swift
- iOS/Example/BeagleDemo/BeagleDemo/Screens/SendRequestScreen.swift
- iOS/Example/BeagleDemo/BeagleDemo/Screens/SimpleForm.swift
- iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj
- iOS/Sources/Beagle/Sources/Action/Action.swift
- iOS/Sources/Beagle/Sources/Action/Types/AddChildren.swift
- iOS/Sources/Beagle/Sources/Action/Types/Alert.swift
- iOS/Sources/Beagle/Sources/Action/Types/Condition.swift
- iOS/Sources/Beagle/Sources/Action/Types/Confirm.swift
- iOS/Sources/Beagle/Sources/Action/Types/FormLocalAction.swift
- iOS/Sources/Beagle/Sources/Action/Types/FormRemoteAction.swift
- iOS/Sources/Beagle/Sources/Action/Types/FormValidation.swift
- iOS/Sources/Beagle/Sources/Action/Types/Navigate.swift
- iOS/Sources/Beagle/Sources/Action/Types/SendRequest.swift
- iOS/Sources/Beagle/Sources/Action/Types/SetContext.swift
- iOS/Sources/Beagle/Sources/Action/Types/SubmitForm.swift
- iOS/Sources/Beagle/Sources/Action/Types/Tests/FormLocalActionTests.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/ActionAttributes.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/RecordFactory.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/Tests/ActionAttributesTest.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/Tests/AnalyticsServiceTests.swift
- iOS/Sources/Beagle/Sources/Analytics/Service/Tests/JSON/SetContext-1.json
- iOS/Sources/Beagle/Sources/Analytics/Service/Tests/__Snapshots__/ActionAttributesTest/attributes.SetContext-1.json
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Form/FormManager/FormManager.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewController.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/Tests/ListViewTests.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Path.swift
- iOS/Sources/Beagle/Sources/Decoding/Tests/ComponentDecoderTests.swift
- iOS/Sources/Beagle/Sources/Setup/Tests/BeagleSetupTests.swift
#745 
By adding the `analytics` attribute to all `Action`, we would create a breaking change inside users custom actions. To avoid that breaking change, we now provide a new protocol called `AnalyticsAction` that defines that attribute. 
That way, users will need to explicitly say they want an `AnalyticsAction` in order to use it.
Examples:
```swift
public protocol Action: Decodable {
func execute(controller: BeagleController, origin: UIView)
}
public protocol AnalyticsAction: Action {
var analytics: ActionAnalyticsConfig? { get }
}
public struct UserCustomAction: Action {
// ...
// No compilation errors
}
public struct UserCustomActionWithAnalytics: AnalyticsAction {
// ...
public var analytics: ActionAnalyticsConfig? = nil
}
```
Please, check if these important points are met using …
> fix: breaking change due to new `analytics` attribute on actions

- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Expression.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Parser.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Tests/ExpressionTests.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Tests/__Snapshots__/ExpressionTests/testContextExpression.1.txt
Fixed a problem related to the parser _singleOrMultipleExpression_. For multiple expression beginning with bind the parser was returning _nil_. Ex: "{expression} + string" 
> fix: iOS - ContextExpression parser

- android/beagle/src/main/java/br/com/zup/beagle/android/components/LazyComponent.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/LazyComponentTest.kt
#1342
Add simple error screen when failed request in lazy component
> feat: add behaviour in lazy component to show error when failed request

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/TextInputTest.kt
- backend/widgets-dsl/src/main/kotlin/br/com/zup/beagle/ui/TextInputBuilder.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/TextInput.kt
- iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/__Snapshots__/TextInputTests/test_whenDecodingJson_shouldReturnAText.1.txt
- iOS/Sources/Beagle/Sources/Components/Widget/TextInput/TextInput+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/Widget/TextInput/TextInput.swift
Issue #1401
create field enabled in text input and deprecated field disabled
> feat: create field enabled in text input and deprecated field disabled

- flutter/beagle/lib/action/beagle_open_native_route.dart
- flutter/beagle/lib/beagle_sdk.dart
- flutter/beagle/lib/bridge_impl/beagle_js_engine.dart
- flutter/beagle/lib/bridge_impl/beagle_service_js.dart
- flutter/beagle/lib/interface/beagle_service.dart
- flutter/beagle/lib/service_locator.dart
- flutter/beagle/test/bridge_impl/beagle_js_engine_test.dart
- flutter/beagle/test/bridge_impl/beagle_service_js_test.dart
- flutter/javascript-bridge/src/global.d.ts
- flutter/javascript-bridge/src/index.ts
- flutter/javascript-bridge/src/operation.ts
Closes #1405 
Created support for custom operations, to solve this issue I simply added the comunication between the JS bridge and the flutter library following the project's patterns.
A single point of warning for this PR is that inside the Beagle Web Core library an operation is defined as following:
The rest operator ('...') allows us to pass as many arguments as we want when using this interface.
It seems though that dart language does not support any operator that would mimic this behavior, what I did instead is create an interface that receives a list of dynamic types. This solutions does not add any additional problems, it only requires that the function parameters be surrounded by brackets ``myCustomFunc([parameter])`` …
> feat: custom operations

- tests/appium/project/src/test/resources/features/LazyComponent.feature
Closes #1375
This scenario is being commented until we find a proper definition on how to treat error on Lazy Component.
> test: commenting lazy component scenario

- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/PageView+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/Tests/PageViewTests.swift
Closes #1433 
Fix PageView memory leak in `currentPage` binding and action `onPageChange`.
See #1433 for sample.
> fix: PageView retain cycle

- backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ListViewScreenBuilder.kt
Correcting listView styles that caused elements to become unconfigured on the screen
> test: fix layout of listView page 

- iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Sources/Beagle/Sources/Renderer/BeagleErrorView.swift
Fixes #1427 
Fixes the bug by creating a completion block that guarantees the retry block call when the controller has already left the memory. We still need to add an automated ui test that validates this on both platforms.
> fix: iOS - ErrorView retry block

- android/beagle/src/main/java/br/com/zup/beagle/android/components/page/PageIndicator.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/page/PageIndicatorTest.kt
Closes #1451 
When passing some color the beagle crashing.
> fix: adjust crash when passing color in page indicator

- iOS/Example/BeagleDemo/BeagleDemo/Screens/NativeViewController.swift
- iOS/Sources/Beagle/Beagle.xcodeproj/project.pbxproj
- iOS/Sources/Beagle/Sources/Analytics/Deprecated/DeprecatedAnalytics.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Form/Form+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Form/Submit/SubmitFormGestureRecognizer.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Lazy/LazyComponent+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Lazy/Tests/LazyComponentTests.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewController.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/ComponentHostController.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/PageView+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/PageViewUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Screen/ScreenComponent+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Screen/Tests/ScreenComponentTests.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/TabBar/TabBar+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/TabBar/TabBarItemUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/TabBar/TabBarUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/Touchable/Touchable+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/WebView/WebViewUIComponent.swift
- iOS/Sources/Beagle/Sources/Components/Widget/Button/Button+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/Widget/Image/Image+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/Widget/TextInput/TextInput+Extensions.swift
- iOS/Sources/Beagle/Sources/ContextExpression/Expression/Expression.swift
- iOS/Sources/Beagle/Sources/Renderer/BeagleRenderer.swift
- iOS/Sources/Beagle/Sources/Renderer/BindingConfigurator.swift
- iOS/Sources/Beagle/Sources/Renderer/LayoutManager.swift
- iOS/Sources/Beagle/Sources/Renderer/Tests/BindingConfiguratorTests.swift
> fix: make unowned references weak

- tests/appium/app-android/app/src/main/AndroidManifest.xml
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AbstractStep.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ActionNotRegisteredScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AddChildrenScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AlertScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AnalyticsScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ButtonScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ConditionalScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ConfirmScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ContainerScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/HookManager.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ImageScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/LazyComponentScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/NavigateScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/PageViewScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ScrollViewScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/SendRequestScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/SetContextScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/SimpleFormScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TabBarScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TextInputScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TextStyleScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TouchScreenSteps.kt
#1438 
Android Appium tests no longer will use a screen to type a text to load a bff screen. Now the bff screens will load by deep link calls. This change reduced the test **run time by over 60%!**
> feat: improved Android Appium tests speed with deep links

- tests/appium/app-android/app/src/main/kotlin/br/com/zup/beagle/appiumapp/activity/BffDeepLinkActivity.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AbstractStep.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/HookManager.kt
#1438
Complementing the merged PR https://github.com/ZupIT/beagle/pull/1470https://github.com/ZupIT/beagle/pull/1470 as I forgot to commit some changes.
> fix: including missing files 

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ActionExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/BindExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/WidgetExtensions.kt
#1414 
Currently, it is not intuitive for the developer as he should evaluate an expression or observe, I made the methods available in the class itself to be easier because the auto-complete will help him.
The names were changed to keep the same name that is on iOS so we will have the same name, making it easier for the developer.
> feat: add function observer and evaluate in bind

- android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/LruImageCache.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/imagedownloader/DefaultImageDownloader.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloaderTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/logger/BeagleMessageLogsTest.kt
This PR fixes an error in the url used in the `ImageDownloader` unit test.
The unit test should not actually download the image, so it was replaced by a mock.
> fix: image downloader test

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/utils/ViewExtensionsKtTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ViewGroupExtensionsKtTest.kt
- android/preview/src/test/java/br/com/zup/beagle/android/preview/PreviewActivityTest.kt
Fixes #1491.
When using the `renderScreen` method to convert a json string in view into multiple fragments within the same activity, there was a conflict with the navigation. Now, the method instead of passing the responsibility to `supportFragmentManager`, it simply replaces the views in the viewGroup with the rendered view.
> fix: renderScreen replacement method

- android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/action/NavigateTest.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Navigate.kt
Closes #1504
This PR adds support to pass expression to `OpenExternalURL`, `OpenNativeRoute` and `PopToView` navigate types.
> feat: added bindable fields to navigate methods

- Beagle.podspec
- Package.swift
Update YogaKit dependency in .podspec and Package.swift
> chore: iOS - Update dependencies in Podspec and Package.swift

- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
Closes #1487 
Toolbar component does not render the title when it is not passed style. 
The expected behavior  should always render the title.
> fix: toolbar set title in beagle android

- .github/workflows/automated_tests_appium_android.yml
> fix: Android Appium GitHub Actions fix

- iOS/Sources/Beagle/BeagleTests/Components/ServerDrivenComponent/PageView/CustomPageIndicator/CustomPageIndicatorTests.swift
- iOS/Sources/Beagle/BeagleTests/Components/ServerDrivenComponent/PageView/PageViewTests.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/PageView+Extensions.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/PageView/PageViewUIComponent.swift
- iOS/Tests/AutomatedTests.xcodeproj/project.pbxproj
Fix #1522
[iOS] Make PageView use all available space like Android does.
> fix: PageView component size

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
Closes #1525
When the HEIGHT property is not set for an imageView on Beagle and just a WIDTH is set, some image resize may occur and the imageView created on **Android** will get its HEIGTH according to the imageSource original HEIGHT. That could add some blank spaces inside the image view since the WIDTH set could be lower than the original source image, what will resize the image to keep its aspect ratio.
This PR fixes this behaviour by adding a property for _Android ImageViews_ called **_"adjustViewBounds"_** . This property adjusts the view bounds from imageView according to the resized image as shown below:
This PR also adds:
* A test to check tha this property is set when a imageView is created in Android ("Then adjustViewBounds should be TRUE as default")
* REFACTOR the ImageTest …
> fix: image resize behaviour

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
Closes https://github.com/ZupIT/beagle/issues/1551
Adjust corner radius in image
- [ X] I am willing to follow-up on review comments in a timely manner.
> fix: adjust image corner radius

- iOS/Sources/Beagle/BeagleTests/Action/Types/__Snapshots__/AddChildrenTests/testDecodingAddChildren.1.txt
- iOS/Sources/Beagle/BeagleTests/Action/Types/__Snapshots__/AddChildrenTests/testDecodingAddChildrenWithDefaultMode.1.txt
- iOS/Sources/Beagle/CodeGeneration/Generated/AutoDecodable.generated.swift
- iOS/Sources/Beagle/Sources/Action/Types/AddChildren+Extensions.swift
- iOS/Sources/Beagle/Sources/Action/Types/AddChildren.swift
#1535
Add support to expression in action AddChildren. See #1535.
BREAKING CHANGE: `AddChildren.value`  type changed from `[ServerDrivenComponent]` to `DynamicObject`
> fix: support expression in action AddChildren

- android/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedTests/config/HttpClientDefault.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/form/core/FormSubmitter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/BeagleApi.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/ComponentRequester.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/data/StringExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/imagedownloader/DefaultImageDownloader.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/networking/HttpAdditionalData.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/networking/RequestData.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleActivity.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleNavigator.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/ScreenRequestMapper.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModel.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/cache/CacheManagerTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/BeagleApiTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/data/ComponentRequesterTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/logger/BeagleMessageLogsTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/mockdata/RequestDataFactory.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/utils/ServerDrivenFactoryKtTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleActivityTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/BeagleNavigatorTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/custom/BeagleViewTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/ScreenRequestMapperTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/MainActivity.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/config/HttpClientDefault.kt
Fixes #1540 
This PR fixes the `RequestData` class constructor and remove all utilization of deprecated params. This will help to change it in 2.0 version.
> fix: android RequestData constructor and utilization

- android/beagle/src/main/java/br/com/zup/beagle/android/context/GlobalContext.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/context/GlobalContextTest.kt
Fixes #1560 
This PR enables `GlobalContext.set` to save any object has a `JsonObject`.
> fix: Android GlobalContext set object

- android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/ImageTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ImageViewFragment.kt
Fixes #1568
Whenever an image is being downloaded or the context of the url is being evaluated or if there is an error in requesting a remote image, the `placeholder` is set, and if there is no drawable, it is removed. This behavior is necessary to prevent previously downloaded images from being displayed in new instances of `ImageView` erroneously. This PR fixes the behavior that removed the drawable from the image when there was a `placeholder` and assigns it instead.
> fix: android image placeholder reset

- backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt
- backend/kotlin-core/src/test/kotlin/br/com/zup/beagle/ext/WidgetExtensionsTest.kt
Closes #1570
Changed to allow use applyStyle and applyFlex in the same implementation.
> fix: allow to use applyStyle and applyFlex in the same implementation

- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewCell.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewController.swift
- iOS/Sources/Beagle/Sources/Components/ServerDrivenComponent/ListView/ListViewUIComponent.swift
Fixes #1581, Fixes #1556
Fixes ListView layout related bugs
> fix: iOS - ListView layout changes (#1556, #1581)

- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/GenericSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/SimpleFormScreenSteps.kt
- tests/appium/project/src/test/resources/features/SimpleForm.feature
> fix: SimpleForm tests

- android/beagle/src/main/java/br/com/zup/beagle/android/components/GridView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/Template.kt
- android/beagle/src/main/java/br/com/zup/beagle/android/components/utils/TemplateJson.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/GridViewTest.kt
- android/beagle/src/test/java/br/com/zup/beagle/android/components/list/ListAdapterTest.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/GridViewFragment.kt
- android/sample/src/main/java/br/com/zup/beagle/sample/fragment/list/ListViewFragment.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/GridView.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/ListView.kt
- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/Template.kt
Changes the `GridView` property `template: ServerDrivenComponent? = null` to `templates: List<Template>? = null` and fixes a bug on `ListView` id manager.
> fix: ListView's manager id and GridView contract

- backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/GridView.kt
> fix: contract adjustment grid view

- .github/workflows/automated_tests_appium_android.yml
- .github/workflows/automated_tests_appium_ios.yml
- .github/workflows/automated_tests_appium_mobile.yml
#1538 
- Make Appium tests run after every merge to Master branch. 
src: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
><img width="738" alt="Screen Shot 2021-06-01 at 12 01 41" src="https://user-images.githubusercontent.com/73198010/120346909-2f743e00-c2d2-11eb-8f3d-944ee29c0ccf.png">
- Enable manually start of Android and iOS Appium tests, because sometimes we need to check specific SO tests under a custom branch
> feat: improve Appium tests CI/CD strategy

- iOS/Sources/Beagle/BeagleTests/Logger/BeagleLoggerProxyTests.swift
- iOS/Sources/Beagle/BeagleTests/Logger/BeagleLoggerTests.swift
- iOS/Sources/Beagle/BeagleTests/Logger/__Snapshots__/BeagleLoggerTests/testLogs.1.txt
- iOS/Sources/Beagle/BeagleTests/Navigation/BeagleNavigatorTests.swift
- iOS/Sources/Beagle/Sources/Logger/BeagleMessageLogs.swift
- iOS/Sources/Beagle/Sources/Navigation/BeagleNavigator.swift
Closes #1612
Closes #1617
Navigation popView changed to pop the stack when there is only one screen in the stack. See #1612 for an example.
> fix: popView with a single view in stack

- android/gradle.properties
- fastlane/Fastfile
- maven-publish.gradle
- tests/appium/app-android/app/build.gradle
- tests/appium/app-android/build.gradle
- tests/appium/app-android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
- tests/appium/app-android/jacoco-android.gradle
- tests/appium/app-android/settings.gradle
- tests/appium/jacoco.gradle
#1620 
[Appium Android app](https://github.com/ZupIT/beagle/tree/master/tests/appium/app-android) no longer includes [Beagle Android](https://github.com/ZupIT/beagle/tree/master/android) modules. The dependency now is through library import. The lib is build and published locally when Appium Android app is compiled. 
> feat: removes module dependency from Beagle and uses lib import instead

- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AbstractStep.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ActionNotRegisteredScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AddChildrenScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/AlertScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ButtonScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ConditionalScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/ConfirmScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/GenericSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TextInputScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/TouchScreenSteps.kt
- tests/appium/project/src/test/kotlin/br/com/zup/beagle/utils/AppiumUtil.kt
- tests/appium/project/src/test/resources/features/ActionNotRegistered.feature
- tests/appium/project/src/test/resources/features/AddChildren.feature
- tests/appium/project/src/test/resources/features/Alert.feature
- tests/appium/project/src/test/resources/features/Button.feature
- tests/appium/project/src/test/resources/features/Conditional.feature
- tests/appium/project/src/test/resources/features/Touchable.feature
#1500 
- Improved test scenarios (ActionNotRegistered, Alert, AddChildren, Button, Conditional and Touchable). More tests will be improved on future PRs
- Improved element locator strategy for iOS. 
> feat: improve Appium iOS tests speed

- flutter/.editorconfig
- flutter/beagle/lib/beagle_sdk.dart
- flutter/beagle/lib/beagle_widget.dart
- flutter/beagle_components/lib/default_components.dart
closes: #1642 
Components and actions are now case-insensitive. Since there were no test-files for `beagle_sdk` and `beagle_widget`, I didn't create new tests for this. Tests for both these files are necessary and should be implemented in a future PR.
I have also:
- created an editorconfig file;
- interpreted some missing components as containers while they're not implemented;
- added an error log when an action is not found.
> fix: components and actions in Flutter are now case insensitive

- flutter/beagle_components/lib/beagle_text.dart
- flutter/beagle_components/test/beagle_text_test.dart
When the `alignment` property is `CENTER` in `Text` component it must be centered both horizontally and vertically. To center the text vertically on Flutter, it must be placed inside a Center widget.
> fix: text component when is aligned to center

- flutter/beagle/lib/utils/enum.dart
- flutter/beagle_components/lib/beagle_scroll_view.dart
- flutter/beagle_components/lib/default_components.dart
- flutter/beagle_components/test/beagle_scroll_view_test.dart
- Created the component BeagleScrollView.
- Fixed bug where null values would cause problems when parsing strings into enums.
I didn't chose between `MaterialScrollBar` and `CupertinoScrollBar` because the documentation of the ScrollBar from Material states that this is done by default:
> Dynamically changes to an iOS style scrollbar that looks like CupertinoScrollbar on the iOS platform.
Observation 1: The current example at `/sample` includes a `Column` as the first component. ScrollViews, in Flutter, don't work when wrapped in Columns. Remove the `Column` if you need the `ScrollView` to work.
Observation 2: Dart has a serious problem when dealing with default values and null values, in summary, it doesn't replace null values by the defaults, it has an implicit `undefined` type and only …
> feat: flutter/scrollView

- flutter/beagle_components/lib/beagle_webview.dart
#1643 
- Fixed problem where the BeagleWebView wouldn't react to a change in the property `url`.
Attention: the example for the Appium tests still doesn't work because Yoga is not yet integrated and because of #1671. I tested the component by manually setting a height for the WebView inside the component BeagleWebView.
> fix: flutter: webview component must react to changes in the url property

- flutter/beagle/lib/default/default_storage.dart
- flutter/beagle/pubspec.yaml
- flutter/beagle/test/default/default_storage_test.dart
remove shared preferences and use memory to save data
> refactor: remove shared preferences and use memory to save data

- fastlane/Fastfile
> fix: adjust deploy release

- fastlane/kdocs/indexTemplate/index.html
- The current cloud front configuration requires that the index.html exposed in bucket s3 of our webpage https://docs-reference.usebeagle.io contain a "/" at the end of the url property in the meta tag.
> fix: docs reference redirect to android page on s3 bucket

- flutter/beagle/pubspec.yaml
- flutter/beagle_components/pubspec.yaml
- flutter/readme.md
- The first version of Beagle Flutter in alpha stage is `0.9.0`.
- A link in the `readme.md` file is fixed.
> fix: flutter version and readme link

- fastlane/kdocs/indexTemplate/index.html
issue: #1688
- This file is responsible for redirecting the page access flow from docs-reference.usebeagle.io to docs-reference.usebeagle.io/backend/br.com.zup.beagle.analytics/. 
- This is due to a bug in Dokka that does not generate a home page for the documentation.
> fix: temporary solution to adjust loop inside page docs

- flutter/beagle/LICENSE
- flutter/beagle/README.md
- flutter/beagle/pubspec.yaml
- flutter/beagle_components/LICENSE
- flutter/beagle_components/README.md
- flutter/beagle_components/pubspec.yaml
To publish any library to pub.dev, it's necessary to follow some rules. This PR adds a license and a readme files and the http library.
> fix: adds license, readme and http library

- flutter/beagle_components/pubspec.yaml
- flutter/sample/pubspec.yaml
To publish any package in pub.dev, it's required that no dependencies be local. Given that, `beagle` dependency in `beagle_components` must be the published one.
> chore: remove beagle local dependency from beagle_components

- .github/workflows/license-check.yml
With this name, this workflow will run for every folders and because it has the same name of the backend,android, and ios.
We could put "PR Check" as required even when there is no changes on platform folders
> feat: Change workflow name

- iOS/Sources/Beagle/Sources/Components/Widget/Text/Text+Extensions.swift
> fix: iOS - Empting acessibilityValue from Text component
